### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by hooray4me** [Pro/dkim-exchange#106]
I cannot get this installed. I've tired in multiple ways. What am I missing?
![image](https://cloud.githubusercontent.com/assets/12399138/11022282/7cc029c0-8620-11e5-9546-1fb5436a489b.png)
Then I don't get the option to install.
![image](https://cloud.githubusercontent.com/assets/12399138/11022285/8e1ba3e8-8620-11e5-90c8-f0384ef24f86.png)
I tired to install offline with out success
![image](https://cloud.githubusercontent.com/assets/12399138/11022287/a51dc896-8620-11e5-9067-df18a45dfbfa.png)

Thoughts?

**Comment by Pro** [comment]
The first message is default for the first start, we should change it to an information message, instead of error.

In the second screenshot it looks like you don't have internet connection or at least the GUI cannot connect to Github.

Regarding the offline installation, there was an error in the install script. Please use this one (https://github.com/Pro/dkim-exchange/blob/master/install.ps1). Just replace the one you downloaded. That should work.

**Comment by parthghetia** [comment]
I have the same issue as the OP. All other applications on the server can utilize the existing network connection. I don't know what could be blocking Configuration.DkimSigner

I have yet to try the offline installation with the updated install.ps1. When I get a chance, I'll let you guys know how it goes.

**Comment by hooray4me** [comment]
The only way I was able to get  it installed was to walk thru each line of the install.ps1 and do it manually.

**Comment by AlexLaroche** [comment]
Do you use any web proxy to filter web access?

**Comment by winterheart** [comment]
I got same issue. My workaround is check/uncheck "Include prerelease versions". After this "Upgrade" button becomes active, and after pressing it application installed correctly.

**Comment by Pro** [comment]
@hooray4me does the workaround with check/uncheck "Include prerelease versions" work for you too?
Can you also test to download the file within PowerShell to see if that works:
https://github.com/Pro/dkim-exchange/archive/v2.1.8.zip
(Howto: http://www.powershellatoms.com/basic/download-file-website-powershell/)

You are using the most recent version (2.1.8)?

@winterheart, @hooray4me which windows server version do you have?

Do you use any Proxy or other software/firewall?

**Comment by winterheart** [comment]
@Pro mine is two identical Windows 2008 R2 SP1 with latest hotfixes and Exchange 2010 SP2 with latest hotfixes (14.3.123.4).
I have direct connection to Internet without restrictive rules from firewall (after pressing "Upgrade" program downloaded needed packages successfully).

**Comment by Shmakovm** [comment]
You could add the option in Configuration.DkimSigner.exe to work through a proxy server (w/wo authorization). Thanks !

**Comment by Pro** [comment]
The best solution for proxy settings would be to use the system default proxy from windows. See: http://stackoverflow.com/a/1939019/869402
Needs to be investigated

**Comment by avoidik** [comment]
There is pull request to second problem with red text.

**Comment by Pro** [comment]
@avoidik I already fixed this a few weeks ago: https://github.com/Pro/dkim-exchange/commit/a111e5716a41237542668c3a9909821135b08bee
(Is not yet in the release)

**Comment by Pro** [comment]
The first problem where the "upgrade" button is disabled is now also fixed in https://github.com/Pro/dkim-exchange/commit/f56cfdc498fbaf3798ca9db5a401ab8a1b80eaf3

(esp. https://github.com/Pro/dkim-exchange/commit/f56cfdc498fbaf3798ca9db5a401ab8a1b80eaf3#diff-80fbe899548913d9af44190d7c253f97R256)

**Comment by Pro** [comment]
Will be released as version 3.0.0
