### ISSUE TITLE
DKIM Eventid error 

### ISSUE THREAD

**Issue by damien-giry** [Pro/dkim-exchange#107]
Release 2.1.8 is a huge improvement for signing NDR/OOF emails :)

FYI, since updating to 2.1.8, I got one error:

```
Signing a mail item according to DKIM failed with an exception. Check the logged exception for details. System.NullReferenceException:
Object reference not set to an instance of an object. at 
Exchange.DkimSigner.DkimSigningRoutingAgent.SignMailItem(MailItem mailItem) in d:\Programmieren\dkim-exchange\Src\Exchange.DkimSigner\DkimSigningRoutingAgent.cs:line 88 at 
Exchange.DkimSigner.DkimSigningRoutingAgent.WhenMessageCategorized(CategorizedMessageEventSource source, QueuedMessageEventArgs e) in
d:\Programmieren\dkim-exchange\Src\Exchange.DkimSigner\DkimSigningRoutingAgent.cs:line 58
```
Br,

**Comment by Pro** [comment]
Thanks for the feedback.
The `reference not set` exception seems to be related to the line
`string smtpAddress = mailItem.Message.Sender.SmtpAddress;`
which means that either `mailItem.Message` or `mailItem.Message.Sender` can be null sometimes. This needs an additional `if` check.

**Comment by semack** [comment]
I have the same issue.
