### ISSUE TITLE
"Suggested DNS Record" and "Existing DNS" fields too small for real entries.

### ISSUE THREAD

**Issue by winterheart** [Pro/dkim-exchange#108]
I installed dkim-exchange 2.1.8 and configured DKIM, but got errors "temperror (no key for signature)" from GMail after checking. It appears that I copied only first part of Suggested DNS record, so my public key has been broken in DNS.
Please add scroll bars or resize fields for "Suggested DNS Record" and "Existing DNS".
![dkim01](https://cloud.githubusercontent.com/assets/81112/11085423/037803a4-8868-11e5-9302-0773255d4877.png)

**Comment by AlexLaroche** [comment]
fd8602adcd80b158c1af6397c1e6b9d8f914ecd0
