### ISSUE TITLE
MS Exchange Transport crash if private key is locked by another app

### ISSUE THREAD

**Issue by stevemayster** [Pro/dkim-exchange#109]
Hello.
Recently install dkim-exchange and faced with issue.
In event log appears a error event like this:
Couldn't load the key key for domain example.com. Error message: Invalid DER format for key. (The process cannot access the file because it is being used by another process.) and when message transport crash and queue database is rebuilded.
Based on my research file maybe locked by antivirus software and backup software.
And now i don't now what to do.
I cannot backup server and i can't stop av software(it's not safe)
Per my understanding transport agent addresses to private key every time then it sign a message.
Is it possible to maybe load key to memory?

**Comment by gogglespisano** [comment]
Are you using 2.1.8?  I think the latest version only loads the keys on start or a settings change.

**Comment by stevemayster** [comment]
Hello gogglespisano.
No at that moment stable version is 2.1.7.
I think we need to wait what will Pro says)

**Comment by Pro** [comment]
You should upgrade to 2.1.8
We (esp. @gogglespisano) did some performance improvement which most probably fixes your issue. In v2.1.7 the key was loaded again for each mail.

One strange thing here:
The EdgeTtansport service should never crash because we catch all exceptions within the signer, so there may still be an issue somewhere else...

**Comment by stevemayster** [comment]
Hello Pro.
Thanks for answer.
In log i found another error 
Watson report about to be sent for process id: 12228, with parameters: E12, c-RTL-AMD64, 14.03.0158.001, edgetransport, mscorlib, S.S.C.CryptographicException.ThrowCryptogaphicException, S.S.Cryptography.CryptographicException, 202c, 02.00.50727.5477.
ErrorReportingEnabled: False
Maybe this help?
I think it's because Kaspersky AV doing something with key.

**Comment by Pro** [comment]
@AlxVD do you also use Kaspersky AV?

@stevemayster does this happen for every email or just some random ones?

**Comment by stevemayster** [comment]
It's random, i do everything to put key in exception in Kaspersky, but i think Kaspersky just don't care about exception and then it read this key error ocurred. Error also ocurred then backup is going on but then it's goes match softer and don't brake exchange transport, just complaints about key is locked,

**Comment by Pro** [comment]
Can you upgrade to v2.1.8?

**Comment by stevemayster** [comment]
Pro it's production so i can do it only on weekend.
I notify you then.

**Comment by stevemayster** [comment]
@Pro To upgrade without Configuration.DkimSigner.exe i need to run uninstall script and then install script,right? Or i can just replace some lib?

**Comment by AlxVD** [comment]
There is no Kaspersky AV on my server.
I'm still at 2.1.7... will try to upgrade.

**Comment by Pro** [comment]
@stevemayster for manual update you can just replace the .dll with the one from here:
https://github.com/Pro/dkim-exchange/tree/master/Src/Exchange.DkimSigner/bin
The file is locked by the MSExchangeTransport service, so you need to stop it for this short time to overwrite it.

Then you should also update the .exe from here (download all the files):
https://github.com/Pro/dkim-exchange/tree/master/Src/Configuration.DkimSigner/bin/Release

**Comment by stevemayster** [comment]
Pro,thanks!

**Comment by stevemayster** [comment]
Hello @Pro! 
I update to 2.1.8 in saturday.
It's quite early to say but i think issue resolved, i don't see any error in App.log.
Thank you and @gogglespisano for great work!
