### ISSUE TITLE
Crash with 3.0-beta and Exchange 2016

### ISSUE THREAD

**Issue by matbech** [Pro/dkim-exchange#118]
The DKIM signer fails to install on Exchange 2016. The following error is logged:

Watson report about to be sent for process id: 15004, with parameters: E12IIS, c-RTL-AMD64, 15.01.0225.042, edgetransport, MimeKit, M.C.DkimSigner..ctor, S.Reflection.TargetInvocationException, 1bae, 01.03.0000.000.
ErrorReportingEnabled: False 

followed by
The worker process crashes continuously on startup: C:\Program Files\Microsoft\Exchange Server\V15\Bin\edgetransport.exe. The service will be stopped.

**Comment by semack** [comment]
I confirm.

**Comment by Pro** [comment]
Thanks for the Info. I'm currently installing Ex2016 on a Windows 2016 VM and will try to reproduce the problem.

**Comment by Pro** [comment]
The problem is that your private key isn't valid. You need to create a new one, if you upgrade from version 2.* to 3.*.
Please read: https://github.com/Pro/dkim-exchange#updating-from-version-2-to-3

I improved the error handling for invalid keys, will upload a new beta release later today

**Comment by matbech** [comment]
I believe to use a correct private key. It has been created with openssl and the public key (.pub) is correctly read (using the Check function) by the DKIM configurator. Maybe the configurator should also verify the private key?
