### ISSUE TITLE
Issues with Priority in Exchange Transport Agents dialog

### ISSUE THREAD

**Issue by matbech** [Pro/dkim-exchange#119]
In the Exchange Transport Agents dialog there are two issues which are most likely related:
- The priority for agents with a priority > 9 (e.g. 10) is displayed as 1
- Moving an agent down (Move Down) which has a priority >= 9 results in the priority of the agent to be set to 1 instead of 10.

![priority](https://cloud.githubusercontent.com/assets/6642109/12075391/15810272-b17f-11e5-87ec-e5921795ad67.png)

**Comment by Pro** [comment]
Will check. Thanks!
