### ISSUE TITLE
Support private key files from OpenSSL

### ISSUE THREAD

**Issue by matbech** [Pro/dkim-exchange#120]
Currently it seems that DKIM agent fails to read private key files (.pem) which contain line breaks at position 65. When creating private keys with openssl, it creates .pem with line breaks at position 65:
openssl genrsa -out private.pem
I believe the DKIM signer should support .pem key files with line breaks.

**Comment by Pro** [comment]
I tested with a key from `openssl genrsa -out private.pem` and it works for me now.

**Comment by matbech** [comment]
Thank you. I get the following error now with my key:

Couldn't load private key for domain abcd.com from C:\Program Files\Exchange DkimSigner\keys\abcd.com.pem: Unable to cast object of type 'Org.BouncyCastle.Crypto.Parameters.RsaPrivateCrtKeyParameters' to type 'Org.BouncyCastle.Crypto.AsymmetricCipherKeyPair'.

**Comment by Pro** [comment]
Unfortunately, the MimeKit DKIM signer expects the key to be of type `AsymmetricCipherKeyPair` thus I had it to change from `AsymmetricKeyParameters`.

If the key is of type `AsymmetricKeyParameters` it means that it is in the PKCS#8 format (and does only contain the private key, not the public key).

Which command did you use to generate your key? Because `openssl genrsa -out private.pem` generates a key pair.

**Comment by matbech** [comment]
I have extracted the private key from PKCS12 .pfx using this command:
openssl pkcs12 -in abcd.com.pfx -nocerts -out abcd.com.pem -nodes

**Comment by Pro** [comment]
What happens, if you take the PKCS12 `abcd.com.pfx` instead of the extracted key? Just to see what happens...

**Comment by matbech** [comment]
I removed the password from the .pfx and verified it was correct. Then tried to select it in the configurator:
The selected key is not a valid private key

**Comment by matbech** [comment]
Maybe you build a the AsymmetricCipherKeyPair from the RSAPrivateCrtKeyParameters object:

```RSAPrivateCrtKeyParameters rsaParameters;
var publicParameters = new RSAKeyParameters(rsaParameters.getModulus(), rsaParameters.getExponent());
var pair = new AsymmetricCipherKeyPair(rsaParameters, publicParameters);
// or new AsymmetricCipherKeyPair(rsaParameters, rsaParameters);?
```

**Comment by Pro** [comment]
And another try. The configurator and signer now supports default RSA private keys and the ones exported from PKCS12 files.

@matbech please try the newly compiled .dll (and configurator) in https://github.com/Pro/dkim-exchange/tree/master/Src/Exchange.DkimSigner/bin

**Comment by matbech** [comment]
The configurator is able to load the private key now. However I get this message from the agent:
"Could not initialize MimeKit DkimSigner for domain  abcd.com: Private key not found."

Please also note the extra whitespace in front of the domain name in the error message.

**Comment by matbech** [comment]
In an earlier comment you mentioned that the DKIM signer requires a AsymmetricCipherKeyPair. However when I look at the documentation it says it expects a AsymmetricKeyParameter:
http://www.mimekit.net/docs/html/M_MimeKit_Cryptography_DkimSigner__ctor.htm

**Comment by matbech** [comment]
MimeKit just merged a related patch I have submitted:
https://github.com/jstedfast/MimeKit/pull/216

It should simplify the required changes now.

**Comment by Pro** [comment]
@matbech thanks again! Totally missed that constructor. Recompiled sources are in the repo. Lets see if this fixes it

**Comment by matbech** [comment]
Thank you. It is working now :-)
