### ISSUE TITLE
Verify private key in DKIM configurator

### ISSUE THREAD

**Issue by matbech** [Pro/dkim-exchange#121]
The configuration should verify the private key file (.pem) assigned to each domain. This helps identifying incorrect private key as early as possible and prevents possible crashes in the DKIM transport agents later.

**Comment by Pro** [comment]
The configurator already checks for valid private keys (see https://github.com/Pro/dkim-exchange/blob/master/Src/Configuration.DkimSigner/MainWindow.cs#L961). The check is performed when you use the `Select key file` button.
This is exactly the same parser/code which the signer uses.
Can you make sure that you are using the 3.0.0-beta version of the configurator. Does it show any error message?

**Comment by matbech** [comment]
Yes I'm using the configurator from 3.0.0-beta and no error is displayed after I selected the private key with the select button.

**Comment by Pro** [comment]
Ok, can you try out the newly compiled dll from here:
https://github.com/Pro/dkim-exchange/tree/master/Src/Exchange.DkimSigner/bin

Download all the files in the corresponding directory for your Exchange server. Then copy the files to `C:\Program Files\Exchange DKIM\` and replace if asked. (You may need to stop the `Microsoft Exchange Transport` service to be able to overwrite them).

Then, when you start the Transport service, do you see any error in the Event Log?

**Comment by matbech** [comment]
"Could not initialize MimeKit DkimSigner for domain  abcd.com: Private key not found."

The private key file has been selected in the configurator and is located at:
C:\Program Files\Exchange DkimSigner\keys\abcd.com.pem

**Comment by Pro** [comment]
The check expected the wrong PEM key format. It should now be fixed.
Please try again and let me know if there are any errors:
https://github.com/Pro/dkim-exchange/tree/master/Src/Exchange.DkimSigner/bin
