### ISSUE TITLE
Controls' anchors

### ISSUE THREAD

**Issue by semack** [Pro/dkim-exchange#127]
Please review and fix controls' anchors in DKIM configurator. They work wrong on windows resize.

**Comment by Pro** [comment]
Do you mean the one from the `Check` button for DNS record? I fixed this already today (not yet in the release): https://github.com/Pro/dkim-exchange/commit/4b78fae343f5df569350fa4618a9da10145c6d14#diff-de0f8b728e5b3bc9677f2bac2f495e98L727

**Comment by Pro** [comment]
Couldn't find any other wrong anchor setting.
