### ISSUE TITLE
Support for Exchange 2013 CU 11

### ISSUE THREAD

**Issue by pavelkos** [Pro/dkim-exchange#132]
Hello! Please add support for latest CU.
https://dl.dropboxusercontent.com/u/11127662/Public.V15.CU11.zip

**Comment by Pro** [comment]
Thanks for the files!
Will download and add support for this version in the coming weekend.
This will then be included in version 3.0.0 (estimated release 17. Jan)

**Comment by Pro** [comment]
In version 3.0.1
