### ISSUE TITLE
Update from 2.1.8 to 3.0

### ISSUE THREAD

**Issue by stevemayster** [Pro/dkim-exchange#134]
Hello.
Sorry for question but i don't fully understand how to update from 2.1.8 to 3.0 manually.
If i don't have dkim GUI installed(Exchange 2010SP3) and create keys by opendkim-genkey do i need to regenerate them? 
Or i must uninstall 2.1.8 and install 3.0?

**Comment by AlexLaroche** [comment]
Yes, you should uninstall 2.1.8 first and install 3.0 after.

opendkim-genkey normally generate key in format PEM.
You shouldn't have to make any changes to your current key format.
It's the XML format that isn't more supported.

**Comment by stevemayster** [comment]
Hello,Alex
Thanks for answer!
