### ISSUE TITLE
Possible mistakes in install.ps1 script?

### ISSUE THREAD

**Issue by semack** [Pro/dkim-exchange#135]
I found [this document](https://technet.microsoft.com/en-us/library/hh135098(v=exchg.150).aspx) and compared dkim install script with it.

For example, notes from install script:
Exchange 2013 SP1 CU4 (15.0.847.32)
Exchange 2013 SP1 CU5 (15.0.913.22)

Information from Microsoft web site:
Exchange Server 2013 CU4 May 27, 2014 15.00.0913.022
Exchange Server 2013 CU5 August 26, 2014 15.00.0995.029

As you see, there is different information about versions.

**Comment by Pro** [comment]
Yes you are right. It looks like we are using a different naming, i.e.,
(left the official, right side our version)
Exchange Server 2013 SP1 -> Exchange 2013 SP1 CU4
Exchange 2013 CU4 -> Exchange 2013 SP1 CU5
Exchange 2013 CU5 -> Exchange 2013 SP1 CU6

Somehow, the official document skips CU6?

**Comment by semack** [comment]
I found this one
http://social.technet.microsoft.com/wiki/contents/articles/15776.exchange-server-2013-and-2016-build-numbers-with-cumulative-updates.aspx

**Comment by Pro** [comment]
This looks more like our scheme. So it should be fine?

**Comment by semack** [comment]
I don't know :)

**Comment by Pro** [comment]
Jep, looks good to me
