### ISSUE TITLE
Invalid from address '<>' and invalid SmtpAddress ''. Not signing email.

### ISSUE THREAD

**Issue by mateuszr89** [Pro/dkim-exchange#137]
Hello, 

I am using version 3.0.1. In EventLog Viewer I have many logs like:

"Invalid from address '<>' and invalid SmtpAddress ''. Not signing email."

Is it normal ?

**Comment by Adam1621** [comment]
I get the same log messages occasionally.  We recently changed email domains. We have added our new domain to dkimsigner but not the old one.  There are still some automated processes sending emails with our old domain so I believe that is why I'm getting these messages. This may not help but thought I'd mention =)

**Comment by Pro** [comment]
The `invalid from address` message is an information output and not an error.
This means that the agent got a mail without a from address, which may be system emails.
You can check your Exchange Messages Log to see which messages those are exactly.

That should be normal behaviour, as log as all you other emails are signed correctly.

**Comment by Adam1621** [comment]
Thank you

Sent from my U.S. Cellular® Android-powered device


-----Original message-----
