### ISSUE TITLE
Value "SytemDrive" is fixed in the code - not read from the system enviroment variable

### ISSUE THREAD

**Issue by AliaWeb** [Pro/dkim-exchange#139]
The Installation works for system drive C: only. If the OS on another disk (eg., D:), then not working properly.

**Comment by Pro** [comment]
Yes, that's correct.
Even though it is not recommended to install windows or applications on another drive than C:, we should support different install paths.
To achieve this, we need a way to let the user define the path stored in https://github.com/Pro/dkim-exchange/blob/master/Src/Configuration.DkimSigner/Constants.cs#L7

**Comment by Pro** [comment]
@AliaWeb fixed in version  3.0.2
