### ISSUE TITLE
Exchange 2013 Toolbox snap fails to start after installing yestarday latest 3.0.1 DKIM-Exchange.

### ISSUE THREAD

**Issue by mitacs** [Pro/dkim-exchange#141]
Hello,

Exchange 2013 SP1 on Windows 2012 R2. Before installing DKIM-Exchange 3.0.1 (manual installation) I applied Exchange2013-KB2938053-FixIt using PowerShell; https://github.com/Pro/dkim-exchange/issues/24. DKIM seems to be working well (other than Windows Event 1057, MSExchange Extensibility - Agent 'Exchange DkimSigner' went async). 
However, whenever I attempt to start Exchange Toolbox (mmc or Windows Icon/shortcut), it crashes.
I am 99% percent sure that Exchange Toolbox was working well after I patched and rebooted this server ~week ago, as I was monitoring message queue after the reboot. I cannot restart the server and see whether the problem goes away until next month.

[Report - Copy.wer.txt](https://github.com/Pro/dkim-exchange/files/138673/Report.-.Copy.wer.txt)

"MMC has detected an error in a snap-in and will unload it"
FX:{714FA079-DC14-470f-851C-B7EAAA4177C1}
Type is not resolved for member 'Microsoft.Exchange.Configuration.MonadDataProvider.MonadDataAdapterInvocationException,Microsoft.Exchange.Configuration.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

Exception type:
System.Runtime.Serialization.SerializationException

Exception stack trace:
  at Microsoft.ManagementConsole.Internal.IMessageClient.ProcessRequest(Request request)
   at Microsoft.ManagementConsole.Executive.RequestStatus.BeginRequest(IMessageClient messageClient, RequestInfo requestInfo)
   at Microsoft.ManagementConsole.Executive.SnapInRequestOperation.ProcessRequest()
   at Microsoft.ManagementConsole.Executive.Operation.OnThreadTransfer(SimpleOperationCallback callback)

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	mmc.exe
  Problem Signature 02:	6.3.9600.17415
  Problem Signature 03:	54504e26
  Problem Signature 04:	MMCEx
  Problem Signature 05:	6.3.9600.16384
  Problem Signature 06:	5215552e
  Problem Signature 07:	754
  Problem Signature 08:	e
  Problem Signature 09:	VZEVNFUPILSVC31Z3H5GTO45URXFKID3
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	df29
  Additional Information 2:	df291ca819a7dfd9eb786c70f2f0186f
  Additional Information 3:	b7fc
  Additional Information 4:	b7fc5e36af54104f3ef4623847c4e676

Please let me know if you need any additional information.

**Comment by Pro** [comment]
Thanks for the bug report!
To me this doesn't look like it is related to the DKIM signer. The only way to find that out is to uninstall it again completely and check if Exchange Toolbox works again.

Did you already read through these:
* https://social.technet.microsoft.com/Forums/exchange/en-US/44c7c769-b495-4bd5-8160-f1803c74dbc1/error-mmc-has-detected-an-error-in-a-snapin-and-will-unload-it?forum=exchangesvrdeploy
* http://www.experts-exchange.com/questions/28177865/Unable-to-use-EMS-after-Exchange-2013-CU1-Upgrade.html
* https://social.technet.microsoft.com/Forums/exchange/en-US/4fcdfb99-f072-4e71-b32c-8f6efcdde7a5/exchange-toolbox-fails-in-mmc?forum=exchangesvrdeploy
* http://www.networksteve.com/exchange/topic.php/Fresh_install,_unable_to_open_Echange_Toolbox_or_EMS/?TopicId=37840&Posts=6

It looks like this is related to some IIS issues.

**Comment by Pro** [comment]
@mitacs any news about this issue?
Please close it if it was resolved and post the solution here. Thanks

**Comment by mitacs** [comment]
Thanks Stefan.

 

I will reboot Exchange server around mid-March and give you update on this issue.

 

Regards,

Marek

**Comment by mitacs** [comment]
We think that we found (by coincidence, troubleshooting Exchange Management Shell issue) the problem, Stefan.

 

I followed this manual DKIM installation instructions:

1.	Execute the following command to allow execution of local scripts (will be reset at last step): Set-ExecutionPolicy Unrestricted
2.	Cd into the folder where the zip has been extracted.
3.	Execute the install script .\install.ps1
4.	Follow the instructions. For the configuration see next section.
5.	Reset the execution policy: Set-ExecutionPolicy Restricted

Step number 5 most likely broke Exchange Toolbox and created this error when opening Exchange Management Shell for us:

 

“File C:\Program Files\Microsoft\Exchange Server\V15\bin\RemoteExchange.ps1

cannot be loaded because running scripts is disabled on this system. For more

information, see about_Execution_Policies at

http://go.microsoft.com/fwlink/?LinkID=135170”

 

The fix is to run “Set-ExecutionPolicy RemoteSigned” so “Get-ExecutionPolicy –List” output looks like this:

 

                                  Scope                         ExecutionPolicy

                                  -----                         ---------------

                          MachinePolicy                               Undefined

                             UserPolicy                               Undefined

                                Process                               Undefined

                            CurrentUser                               Undefined

                           LocalMachine                            RemoteSigned

 

Both Exchange Toolbox and Exchange Management Shell are working now. Please test it yourself and let me know whether the problem was somehow only related to our environment. And if not, please update your installation instructions and close this bug report.

 

Thanks,

Marek

 

From: Marek Biela 
Sent: February-29-16 2:41 PM
To: 'Pro/dkim-exchange'; Pro/dkim-exchange
Cc: sysadmin
Subject: RE: [dkim-exchange] Exchange 2013 Toolbox snap fails to start after installing yesterday latest 3.0.1 DKIM-Exchange. (#141)

 

Thanks Stefan.

 

I will reboot Exchange server around mid-March and give you update on this issue.

 

Regards,

Marek

**Comment by Pro** [comment]
@mitacs thans for your valuable feedback! I updated the install instructions according your suggestions.
