### ISSUE TITLE
no mail coming after installing Configuration.DkimSigner

### ISSUE THREAD

**Issue by verykindwolf** [Pro/dkim-exchange#142]
I have Exchange Server 2010. Just after I installed DkimSigner, I can send mail out, I can send and receive mail inside, but no mail can be received from outside. After sanding to my server I get such answer: host said: 452 4.3.1  Insufficient system resources (in reply to MAIL FROM command)

**Comment by Pro** [comment]
This is probably not related to DKIM since it is a resources problem (as the error messages says).
Normally this means that you don't have enough RAM (very minimum 4GB) or HDD space.
Please check this in the Task Manager.

Also check the EventLog if there are any related Error Messages.

**Comment by verykindwolf** [comment]
Yep. It seems you r right. I cleaned HDD, making more of 4% of HDD free space as mails started coming in.One thing is not clear, why DkimSigner installation provoked  'Insufficient system resources' error.
