### ISSUE TITLE
Could not extract public key from dns record

### ISSUE THREAD

**Issue by spid3r1987** [Pro/dkim-exchange#143]
Help!!
i have installed the DKIM-Exchange via the online installer.
configured everything, but getting the error of could not extract public key from dns record.

i have noticed that there is the issue fix, but i do not have the files mentioned on my server to edit the file.

how can i resolve this issue?

Regards
michael

**Comment by Pro** [comment]
Which version did you install?

Can you post the content of the two text fields "suggested DNS record" and "existing DNS record"?

**Comment by spid3r1987** [comment]
Version is 3.0.2
suggested has 
"v=DKIM1; k=rsa; p=<KEY REMOVED>"
existing has nothing then below says could not extract public key from dns record

**Comment by Pro** [comment]
Note: You don't need to remove the public key, since it will be publicly visible anyway.
Did you setup you DNS record correctly? Did you press the "check DNS" button?

**Comment by spid3r1987** [comment]
ahh right ok lol.
suggested :
"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmw0KIrvuofz5rC6moCHB21Y9ucwtVPLKtEn8FNraJ70X3IpvXQgonwJg/MpNobtbmIjFuBJ231/FkgVfGv284c8TSuWnqKmJ0T5YibZIX9qrSnMALwyj9clMkD2jt6gcgeGH+59BkeN44sn1RCNWqe4DDWJukfB2wh1GkzA1HQiaChdHXntizps7P5IIoJdWgn5b0a0608LoNRfgg8r8zjXsQ115mZR9kALPcHuiLTV3iD+TjhttQGn4z3xdB5FnsqIkHbWXvygX71q8JjeGMO0wtKCSkXNUTQb3dVMAF8CzpXbWmhV1dEc94lh/E8TcyfeQDeFq4Gz+/8upfzvQzwIDAQAB"

Existing dns:
"blank"
could not extract public key in red at the bottom after pressing the check dns button

**Comment by Pro** [comment]
Please check you DNS record with a tool like http://www.protodave.com/tools/dkim-key-checker/ or Google for another checking tool

**Comment by spid3r1987** [comment]
not showing any dns txt record found.... strange

**Comment by Pro** [comment]
Make sure you set up the DNS correctly. Then DKIM Signer will find the record.

**Comment by spid3r1987** [comment]
Never mind. Found a different tool and it's all sorted now mate. Thanks anyway



Sent from my Samsung device


-------- Original message --------

**Comment by lukehamburg** [comment]
Could be that you are using split DNS and only set the DKIM record on your public facing DNS (eg Network Solutions, GoDaddy etc) and forgot to add it to the internal side? I saw that myself. It is harmless anyway.

**Comment by spid3r1987** [comment]
I set the records on my hosted dedicated server which controls various domains. And on my local sbs server to cover both angles incase it was looking at the hosted dedicated server rather than local server.



Sent from my Samsung device


-------- Original message --------
