### ISSUE TITLE
Exchange 2013 Edge Transport stops signing DKIM until restarted

### ISSUE THREAD

**Issue by jho1670** [Pro/dkim-exchange#144]
Exchange 2013 Edge Transport 15.0.1156.6
Running 3.0.1 (just upgraded to 3.0.2, will try again...)

I set things up, and send mail, and confirm that a) DNS records are correct, b) outbound mails are correctly signed.

Some time later, mails stop getting signed.

I open the Configuration utility, restart the Exchange Edge Transport service, and outbound mails are again properly signed.

What logs should I provide to debug this issue?

**Comment by Pro** [comment]
Did it happen again?
If yes, can you please enable Debug Logging and wait until it happens again. Then we need the events from the Event Log

**Comment by Pro** [comment]
Since there are no new update I'll close this issue. Report back if this problem still occurs.
