### ISSUE TITLE
Manual installation 

### ISSUE THREAD

**Issue by AlwindB** [Pro/dkim-exchange#148]
### Versions
- **Windows Server Version**: Windows Server 2008r2
- **Exchange Version**: 2010 v14.30.0266.001 / v14.03.0294.000
- **Installed DKIM Exchange Version**: 3.0.2/3.0.3
### Description

When trying to install manually using the described procedure we encounter issues in the install.ps1 script, notifying us about Unblock-File errors. This is correct as 2008r2 does not have PowerShell v3 installed by default.

When starting the Exchange Transport Service an error is thrown after not being able to start the Windows service in the Application Eventlog.

Event id 4999
Watson report about to be sent for process id: 15076, with parameters: E12, c-RTL-AMD64, 14.03.0266.001, edgetransport, ExchangeDkimSigner, E.D.DkimSigningRoutingAgentFactory..ctor, S.Reflection.TargetInvocationException, 6d6d, 03.00.0002.-001.
ErrorReportingEnabled: False

The transport agent won't start at all.

Have tried it on 2 separate servers, both running different versions of Exchange 2010

So far a no-go on 2010, any way we can provide you with more information to troubleshoot this?

**Comment by Pro** [comment]
I think that the files aren't unlocked successfully and then if Exchange tries to open the files it crashes.

You can check if the files are still locked by opening the file properties dialog (e.g. on `C:\Program Files\Exchange DkimSigner\ExchangeDkimSigner.dll`). It should look something like this:
![image10](https://cloud.githubusercontent.com/assets/251973/14151175/fb9b59f2-f6ac-11e5-809a-0c5652735ecc.png)

Or use the cmd:
```
cd "C:\Program Files\Exchange DkimSigner"
dir /r .
```
If you see files ending with `:Zone.Identifier:$Data` the files are locked.

To unlock the files, open all the files manually and press `Unlock` or use the following command in cmd (not tested): `streams -s -d "C:\Program Files\Exchange DkimSigner"`

Source: http://www.howtogeek.com/70012/what-causes-the-file-downloaded-from-the-internet-warning-and-how-can-i-easily-remove-it/

Does this work?

**Comment by AlwindB** [comment]
The screenshot you posted does not match the interface with Windows Server 2008 r2, the unblock function in simply missing from it. Streams by SysInternals might be a solution.

I'll update you with further information as soon as I have it, I'll have a look at it with the Sysadmin of that server.

**Comment by Pro** [comment]
@AlwindB any updates on this?

**Comment by f3rik** [comment]
Hey Pro,

I want to install it on a Windows Server 2008r2 with Exchange 2010 SP1 and is asking for .net 4.5 as requirements but my operating system is not suporting 4.5 only 4.0.

In the troubleshooting guideline I saw that there is an option to change the target framework to .NET 3.5 but  unfortunately I am not able to do that is keep throwing me some errors that some parts are missing. I am probably not an expert in Visual Studio... :) 

Can you do that for me and rebuild for .net 3.5 in order to be able to install?

**Comment by DJBenson** [comment]
Closing stale issue.
