### ISSUE TITLE
The TransportAgentFactory type "Exchange.DkimSigner.DkimSigningRoutingAgentFactory" doesn't exist.

### ISSUE THREAD

**Issue by FortKnox77** [Pro/dkim-exchange#149]
### Versions

- **Windows Server Version**: 2012 R2
- **Exchange Version**: 15.1.396.30

Hello,
I need advice with the following error, I can not install agent

Error:
[PS] C:\Windows\system32>Install-TransportAgent -Name "Exchange DKIM" -TransportAgentFactory "Exchange.DkimSigner.DkimSi
gningRoutingAgentFactory" -AssemblyPath "C:\DK\ExchangeDkimSigner.dll"
The TransportAgentFactory type "Exchange.DkimSigner.DkimSigningRoutingAgentFactory" doesn't exist. The TransportAgentFa
ctory type must be the Microsoft .NET class type of the transport agent factory.
Název parametru: TransportAgentFactory
    + CategoryInfo          : InvalidArgument: (:) [Install-TransportAgent], ArgumentException
    + FullyQualifiedErrorId : [Server=SQL,RequestId=97a02efb-36d2-4816-948c-1535db456bfc,TimeStamp=14. 4. 2016 16:27:3
   5] [FailureCategory=Cmdlet-ArgumentException] 424F53F2,Microsoft.Exchange.Management.AgentTasks.InstallTransportAg
  ent
    + PSComputerName 

Thank you

**Comment by Pro** [comment]
This looks like you are using the wrong `ExchangeDkimSigner.dll`
Can you make sure that you are using the correct one in `C:\DK\ExchangeDkimSigner.dll` In your case it should be Exchange 2016 CU1: https://github.com/Pro/dkim-exchange/tree/master/Src/Exchange.DkimSigner/bin/Exchange%202016%20CU1
Copy all the files from this directory to your `C:\DK\` directory.

Also have a look at the commands used in https://github.com/Pro/dkim-exchange/blob/master/install.ps1

**Comment by Pro** [comment]
Please also check if your files are unlocked: https://github.com/Pro/dkim-exchange/blob/master/TROUBLESHOOT.md#solution

**Comment by FortKnox77** [comment]
Library version 3.0.3 is correct, and the files are not locked.

Unfortunately, the error is still the same

**Comment by Pro** [comment]
Just to be sure: It isn't enough if the library version is correct, you also have to take the correct .dll for your specific Exchange Version

Can you also try to use the install.ps1 script instead of your manually typed command?

If that doesn't work, send me the .dll files as described here:
https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md#how-to-include-support-for-newer-exchange-versions

**Comment by FortKnox77** [comment]
Unfortunately, I ended up compiling a mistake and I did not compile it, I have no idea where the problem is.

**Comment by Pro** [comment]
Please try the install script or the installer, that should work. If not, please reopen this issue.
