### ISSUE TITLE
Exchange DKIM signer not signing

### ISSUE THREAD

**Issue by Lud3rik** [Pro/dkim-exchange#151]
### Versions

- **Windows Server Version**: Windows Server 2012 R2 Datacenter
- **Exchange Version**: Exchange 2013 -- > 0.1 (8.0.535.0) 
- **Installed DKIM Exchange Version**: 3.0.3

### Description
Exchange is not signing my mails with DKIM. The settings are loaded on 1 domain.
When I check, I see in green letters DNS record public key is correct.
I have done my record with the selector default.

### Steps to Reproduce

1. Install Exchange DKIM Signer on Exchange 2013
2. Generate your keys with RsaSha256
3. Configure selector default and sub.yourdomain.com
2. Deploy your public key on your favorite DNS registrar
3. Validate your record in the Exchange DKIM Signer console
4. Check in the Event Log that your settings are loaded
5. Send a mail to mailtest@unlocktheinbox.com
6. Receive some bad news like : 
Publication: RFC 6376
DKIM Check
Tag	Value
Signature Found:	Not Found - Learn how to set up DKIM by clicking here: DKIM Instructions

**Expected behavior:** [What you expected to happen]

DKIM Signature should be validated

**Actual behavior:** [What actually happened]

DKIM Signature is not validated as the software is not working properly.

That you for your help

**Comment by Pro** [comment]
Can you set the event logging to debug. Then check the output in the event log when you send an email. Is there anything unusual?

**Comment by Lud3rik** [comment]
I see something like:

DEBUG: No entry found in config 'mydomain.com'
DEBUG:Got new message, checking if I can sign it...

It's a little weird as my mail server is recorded in a subdomain, which is mail.mydomain.com
And the configuration I made in DKIM Setting is related to the subdomain.

**Comment by Pro** [comment]
Can you post the content of your .xml settings file `C:\Program Files\Exchange DkimSigner\settigs.xml` (replace your domain with e.g. example.com if you need to, but leave the subdomain settings as they are)

**Comment by Lud3rik** [comment]
Hereby the settings

<?xml version="1.0" encoding="utf-8"?>
<Settings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Loglevel>4</Loglevel>
  <SigningAlgorithm>RsaSha256</SigningAlgorithm>
  <HeaderCanonicalization>Simple</HeaderCanonicalization>
  <BodyCanonicalization>Simple</BodyCanonicalization>
  <HeadersToSign>
    <string>From</string>
    <string>Subject</string>
    <string>To</string>
    <string>Date</string>
    <string>MessageId</string>
  </HeadersToSign>
  <Domains>
    <DomainElement>
      <Domain>mail.example.com</Domain>
      <Selector>default</Selector>
      <PrivateKeyFile>mail.example.pem</PrivateKeyFile>
    </DomainElement>
  </Domains>
</Settings>

**Comment by Pro** [comment]
What is your email adress? `name@example.com`?
Then you have to use `example.com` as your Domain setting.

**Comment by Lud3rik** [comment]
Okay thank you I will try this.
So can you confirm that I need to:

update my dns record in the registrar
update the domain in DKIM signer
restart transport service

**Comment by Pro** [comment]
Use the configurator and then set the domain to `example.com`
Use the suggested DNS record in your registrar (yes you need to update DNS depending on your current setting).
The transport service does not need to be restarted since the DKIM signer automatically reloads configuration changes.

**Comment by Lud3rik** [comment]
Ok thank you
Now my record on the registrar DNS looks like:
default._domainkey 10800 IN TXT "v=DKIM1;" "k=rsa; p=MIIB[...]
It was previously set like
default._domainkey.mail 10800 IN TXT "v=DKIM1;" "k=rsa; p=MIIB

**Comment by Pro** [comment]
Looks good, does it work with these settings? If yes, please close this bug report. Thanks

**Comment by Lud3rik** [comment]
I need to w8 3h for the DNS to progate settings but I will keep you informed

**Comment by Lud3rik** [comment]
Awesome it works perfectly.
Thank you for your help and you support.
Glad to use a homemade opensource software for DKIM :)

Best regards
