### ISSUE TITLE
Support for Exchange 2016 CU2

### ISSUE THREAD

**Issue by jefferson-1** [Pro/dkim-exchange#153]
### Versions

- **Windows Server Version**: Server 2012R2
- **Exchange Version**: Exchange 2016 CU2 (15.01.0466.034)
- **Installed DKIM Exchange Version**: Can't install

### Description

Cannot use automated install to install DKIM current version.

### Steps to Reproduce

1. Install Server 2012R2
2. Install Exchange 2016
3. Install CU2 / .NET Framework 4.6.2

**Expected behavior:** Install complete.

**Actual behavior:** Install failed with error that current version isn't supported.

If interested, I'd be happy to do a pull and to just update the dll's and so forth to CU2 (same as what another contributor did).

**Comment by Pro** [comment]
That would be great.

Please see the documentation here on how to do this:
https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md#how-to-include-support-for-newer-exchange-versions

**Comment by jefferson-1** [comment]
Posted all changes. Note -- I haven't tested. For something like this, I'll test on the live server after hours...

**Comment by jefferson-1** [comment]
Tested fine on live server. Proposing a merge with main branch.

**Comment by Pro** [comment]
Thank you very much!!
I'll merge it and create a new release in the coming days.

**Comment by jefferson-1** [comment]
Welcome :)

Sent from my iPhone

On Jul 12, 2016, at 12:25 PM, Stefan Profanter <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you very much!!
I'll merge it and create a new release in the coming days.

-
