### ISSUE TITLE
CU13

### ISSUE THREAD

**Issue by cassioac** [Pro/dkim-exchange#155]
Hi, just curious on when will the CU13 update be available.

Thanks

**Comment by Pro** [comment]
I need the corresponding .dll files for that.
See: https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md#how-to-include-support-for-newer-exchange-versions

**Comment by cassioac** [comment]
So I should disable dkim signer, install cu13 to harvest files and wait for the update?

Sent from my iPhone

On Jul 16, 2016, at 11:14, Stefan Profanter <notifications@github.com<mailto:notifications@github.com>> wrote:


I need the corresponding .dll files for that.
See: https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md#how-to-include-support-for-newer-exchange-versions

-

**Comment by cassioac** [comment]
Or I could just install on a test server lol.

thanks, I’ll provide the files soon

On Jul 16, 2016, at 11:21 AM, Cassio Simoes <cassio@iphonesp.com.br<mailto:cassio@iphonesp.com.br>> wrote:

So I should disable dkim signer, install cu13 to harvest files and wait for the update?

Sent from my iPhone

On Jul 16, 2016, at 11:14, Stefan Profanter <notifications@github.com<mailto:notifications@github.com>> wrote:


I need the corresponding .dll files for that.
See: https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md#how-to-include-support-for-newer-exchange-versions

**Comment by kubik256** [comment]
EXCHNAGE 2013 CU13 files are here: https://drive.google.com/file/d/0B-02UcncQWLTRlNuRWVNdkIwZU0/view?usp=sharing

**Comment by cassioac** [comment]
Thanks kubik256, although I said I would, I didn't have time to do this myself.

**Comment by kubik256** [comment]
No problem. Unfortunately I'm not much familliar with C#, so thanks to anyone who will do the code part :)

**Comment by k6row** [comment]
I have also already created a pull request for this, with the required files attached

**Comment by nsumner36** [comment]
Is there any update on this at all. If you need the files still I will be happy to provide them!

**Comment by impoole** [comment]
Any update, we're also stuck with CU13

**Comment by Pro** [comment]
Sorry for the late reply, I'll add support for the latest Exchange Versions this weekend.

**Comment by Pro** [comment]
Done and released: https://github.com/Pro/dkim-exchange/releases/tag/v3.0.5

**Comment by impoole** [comment]
Many thanks, that’s great – saved me rolling back to CU12!
