### ISSUE TITLE
domain config, 'selector' field?

### ISSUE THREAD

**Issue by mettix** [Pro/dkim-exchange#158]
### Versions

- **Windows Server Version**: [2008R2]
- **Exchange Version**: [2010SP3]
- **Installed DKIM Exchange Version**: [latest]

### Description

Selector setting? Hello, on the domain configuration tab there is a field named selector, what should I input there? (servername?)

Thanks in advance.

**Comment by VladlenBulatov** [comment]
selector is name of DNS record -
selector: 20160904
domain: example.com
full name for record are - (TXT) 20160904._domainkey.example.com

**Comment by mettix** [comment]
Hello,

Yes it is working meanwhile. Will the app be updated to support the latest Exchange 2013 CU release?
Thanks!

**Comment by Pro** [comment]
Sorry for the late reply, I'll add support for the latest Exchange Versions this weekend.
