### ISSUE TITLE
Support for Exchange 2013 CU14

### ISSUE THREAD

**Issue by ciezakj** [Pro/dkim-exchange#163]
### Versions

- **Windows Server Version**: [2k12R2]
- **Exchange Version**: [2013 CU14]
- **Installed DKIM Exchange Version**: [3.0.5]

### Description

Is Exchange 2013 no longer supported? I can see the support for 2013 CU3 but not for 2013 CU14.
Regards
Jack

**Comment by Pro** [comment]
I don't have the required .dll files.
See: 
https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md#how-to-include-support-for-newer-exchange-versions

**Comment by sidgms** [comment]
I have already created a pull request for this.

**Comment by Pro** [comment]
Released as v3.0.7
Thanks!
