### ISSUE TITLE
MSExchange 2007 Transport won´t start with DKIM SIgner 

### ISSUE THREAD

**Issue by scifire91** [Pro/dkim-exchange#165]
### Versions

- **Windows Server Version**: [Windows Server 2008R2 SP1]
- **Exchange Version**: [Exchange Server 2007 8.03.0083.000] 
- **Installed DKIM Exchange Version**: [3.0.7]

### Description

Installation and configuration works finde. Problem is if i want to enable the DKIM Signer with the gui the Transport Service won´t start anymore.

### Steps to Reproduce

1. Start Exchange DKIM Signer
2. Stop Transport Service, go configure and enable Transport Agent "Exchange DkimSigner" 
3. Gui hangs up, if restart the gui the ETA is enabeld but Transport Service won´t start
4. Disable the ETA Exchange DKIMSigner and start the Transport Agent
5. All is fine again (but no DKIM :( )

**Expected behavior:** Have some fix or workaround

**Actual behavior:** Work without DKIMSigner

Edit: Same problem after update exchange to  [8.03.0298.001]

**Comment by scifire91** [comment]
Now Exchnage is last Version [08.03.0485.001] Still the same Problem

**Comment by Monki77** [comment]
Exact same problem here.
I think this is related to Exchange though and not the DKIM Signer. I tried this one _https://bitbucket.org/OmniFinancial/bigglesworth_ and the same thing happens.

**Comment by Pro** [comment]
We had this problem in the past when the .dlls changed during an exchange update. It should be enough to recompile for this specific version.

Can you please upload the required .dll files and post the link here so that I can try it out:
https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md#how-to-include-support-for-newer-exchange-versions

**Comment by scifire91** [comment]
@Pro Unfortunately it doesn't work with this version. Same problem as before

**Comment by Pro** [comment]
Hm, ok, that's bad, but it was worth a try.
Since Ex 2007 will not be supported by microsoft after april 2017 I don't plan to spend too much effort in supporting exchange 2007 at all.

**Comment by scifire91** [comment]
Sure, understandable.... Anyway thanks for the work and the try to fix it.
