### ISSUE TITLE
Exchange 2010 Transport service crashes after DKIM installation

### ISSUE THREAD

**Issue by Olexunder** [Pro/dkim-exchange#166]
### Versions
- **Windows Server Version**: Windows Server 2012 R2 64-bit
- **Exchange Version**: Exchange Server 2010 Version: 14.03.0319.002
- **Installed DKIM Exchange Version**: 3.0.7

### Description

After installation service can't run.
Error:"Description:
Watson report about to be sent for process id: 6476, with parameters: E12, c-RTL-AMD64, 14.03.0319.002, edgetransport, ExchangeDkimSigner, E.D.DkimSigningRoutingAgentFactory..ctor, S.Reflection.TargetInvocationException, 6d6d, 03.00.0007.-001.
ErrorReportingEnabled: False
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MSExchange Common" />
    <EventID Qualifiers="16388">4999</EventID>
    <Level>2</Level>
    <Task>1</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-12-08T10:44:14.000000000Z" />
    <EventRecordID>264823</EventRecordID>
    <Channel>Application</Channel>
    <Security />
  </System>
  <EventData>
    <Data>6476</Data>
    <Data>E12</Data>
    <Data>c-RTL-AMD64</Data>
    <Data>14.03.0319.002</Data>
    <Data>edgetransport</Data>
    <Data>ExchangeDkimSigner</Data>
    <Data>E.D.DkimSigningRoutingAgentFactory..ctor</Data>
    <Data>S.Reflection.TargetInvocationException</Data>
    <Data>6d6d</Data>
    <Data>03.00.0007.-001</Data>
    <Data>False</Data>
    <Data>
    </Data>
  </EventData>
</Event>"

### Steps to Reproduce

1. Install DKIM

**Expected behavior:** [What you expected to happen]
running service 
**Actual behavior:** [What actually happened]
service won't run

**Comment by Olexunder** [comment]
When I disable DKIM agent for Exchange - Transport service starts normally.
Wghen I enable agent again - Transport service crashes.

**Comment by Pro** [comment]
Did you install a recent update for Exchange 2010?

We had this problem in the past when the .dlls changed during an exchange update. It should be enough to recompile for this specific version.

Can you please upload the required .dll files and post the link here so that I can try it out:
https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md#how-to-include-support-for-newer-exchange-versions

**Comment by Pro** [comment]
@Olexunder please send me the files as mentioned here https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md#how-to-include-support-for-newer-exchange-versions so I can add support for Exchange 2010 SP3 RU15

**Comment by Olexunder** [comment]
I have Exchange 2010 sp3 rollup update 15

**Comment by Olexunder** [comment]
I have another remark.
We installed Exchange 2010 on Windows Server 2012R2. Formally it is unsupported configuration by Microsoft. Is it important?

**Comment by rbfajardo** [comment]
.Net framework version is probably different version in Server 2012R2. Considering this is old, maybe it should be closed?

**Comment by DJBenson** [comment]
Closing as per @rbfajardo suggestion.

Please also refer to #293 as Exchange 2010 is EOL soon and will be deprecated from DKIM-Exchange shortly afterwards.
