### ISSUE TITLE
Exchange 2016 CU4

### ISSUE THREAD

**Issue by jaapwess** [Pro/dkim-exchange#167]
Hi,

No issue, but I can confirm the DKIM Signing module works with Exchange 2016 CU4.
Do you have any plans to write a DKIM Verify module?

Thanks,
Jaap Wesselius

**Comment by Pro** [comment]
Thanks for the info! Did you recompile something, or just used the one from CU3?

There aren't any plans to develop a verify module, unfortunately I don't have enough spare time. Pull requests are always welcome. (See #161)

**Comment by jaapwess** [comment]
Hi,

I installed it on CU2, then upgraded to CU3 and now to CU4 (not available yet, I’m in the Microsoft TAP program). Use it for my lab environment and blogged about it: https://jaapwesselius.com/2016/08/22/senderid-spf-dkim-and-dmarc-in-exchange-2016-part-ii/

I would love to see a verify module though, preferably without any appliance or cloud service.
What does it take to get you considering this? ☺

Thanks,
Jaap Wesselius

**Comment by rtenklooster** [comment]
I tried installing it to a new 2016 CU4 installation. It failed because it's  not (yet) supported.
However i modified the install.sh and the lib /  src folders.
Just added the CU4 to the file and copied the CU3 content to a new folder.
Works perfectly now.

**Comment by Pro** [comment]
@rtenklooster thanks for the info. A new version supporting CU4 officially will be released in a few minutes.

@jaapwess to add a verify module it requires some hours of work which I currently don't have. Hopefully in 2017 I will have more spare time to have a look at it on how to implement DKIM verification.
As already said, pull requests are always welcome, and some beers (https://pledgie.com/campaigns/28487) :)

**Comment by jaapwess** [comment]
At first my thought was to drive to Munich to buy you some beer, but donating it is faster. Don’t get too drunk ☺

**Comment by Pro** [comment]
@jaapwess verifier is in progress:
https://github.com/Pro/dkim-exchange/tree/feature/dkim-verify
