### ISSUE TITLE
Transport Role Does Not Start

### ISSUE THREAD

**Issue by tuitioner** [Pro/dkim-exchange#173]
### Versions

- **Windows Server Version**: [2003 R2]
- **Exchange Version**: [2007 SP3]
- **Installed DKIM Exchange Version**: [3.0.8]

### Description
Service TransportRole is not start. In events:

Event Type:	Error
Event Source:	MSExchange Common
Event Category:	General 
Event ID:	4999
Date:		30.03.2017
Time:		14:52:38
User:		N/A
Computer:	HSH-EXCH
Description:
Watson report about to be sent to dw20.exe for process id: 7996, with parameters: E12, c-RTL-AMD64, 08.03.0389.002, edgetransport, unknown, E.D.DkimSigningRoutingAgentFactory.ctor, S.IO.FileNotFoundException, 277a, unknown.  ErrorReportingEnabled: False

For more information, see Help and Support Center at http://go.microsoft.com/fwlink/events.asp.

### Steps to Reproduce

1. Try to Install manualy
2. Ganare keys
3. Settings make on another PC (In Windows 2003 Server - Mistake with run a Configuration.DkimSigner)

[settings.zip](https://github.com/Pro/dkim-exchange/files/882299/settings.zip)

**Expected behavior:** TransportRole is UP

**Actual behavior:** TransportRole is DOWN

**Comment by Pro** [comment]
Does the agent work, if you generate the settings on the Exchange Server directly?
The error message says, that probably the settings.xml file was not found by the signer. Make sure that it is at the same location where the .dll is stored.

I have never tested Windows Server 2003 and it will also not be supported by this signer.

**Comment by Pro** [comment]
Close as wontfix. Windows Server 2003 will not be supported.
