### ISSUE TITLE
Domain Sorting?

### ISSUE THREAD

**Issue by PetieM** [Pro/dkim-exchange#174]
### Versions

- **Windows Server Version**: 2008 R2 Datacenter SP1
- **Exchange Version**: 14.03.0319.002
- **Installed DKIM Exchange Version**: 3.0.8

### Description

This is really minor but I couldn't find a better place to request it. Please let me know if I should do this elsewhere.

I have a large number of accepted domains I'm working with. I love the DKIM signer utility and this would really just be a QoL addition for me in particular but would it be possible to sort the domain list alphabetically (or to offer an option to do so)? Like I said, it's incredibly minor but would help as I go through domains that are being added/removed. Thanks!

**Comment by Pro** [comment]
Thanks for the suggestion.
That's indeed just one click in the Visual Studio designer, setting the ListBox.Sorted property (https://msdn.microsoft.com/en-us/library/system.windows.forms.listbox.sorted(v=vs.110).aspx)

I'll include that in the next release, which will be released hopefully soon!
