### ISSUE TITLE
Could not sign message: the list of headers to sign should not include the unknown headers

### ISSUE THREAD

**Issue by termsl** [Pro/dkim-exchange#177]
### Versions

2012R2- **Windows Server Version**: [Your version]
14.3.123.4- **Exchange Version**: [Your version]
3.0.9- **Installed DKIM Exchange Version**: [Your version]

### Description

Hi, DKIP isnt sign messages, in log many same records
"Could not sign message: the list of headers to sign should not include the unknown headers"

![image](https://cloud.githubusercontent.com/assets/3257553/25992455/3dc67d9a-370f-11e7-99e0-921c996a600d.png)

**Comment by julianmaria** [comment]
The same here.

**Comment by zrbite2k** [comment]
Am seeing same issue (messaged not being signed) and event log with message "Could not sign message: The list of headers to sign SHOULD NOT include the 'Unknown' header.
2008R2, Exchange 14.3.123.4, DKIM Exchange 3.0.10

**Comment by zrbite2k** [comment]
I downgraded to 2.1.8 and that version is working so am using that now. I also tried 3.0.2 earlier but also resulted in the same problems.

**Comment by Digitint** [comment]
Same situation here with recent version.
Windows Server 2008 R2, Exchange 2007 8.3.83.6
DKIM Exchange 3.0.13
Error message: "Could not sign message: The list of headers to sign SHOULD NOT include the 'Unknown' header."
There is also a warning message before error: "Invalid value for header to sign: 'Message-ID'. This header will be ignored."

Error goes away if I remove Message-ID header.

**Comment by Pro** [comment]
Fixed in https://github.com/Pro/dkim-exchange/commit/985d45207d8509521c9324685311c9a57657709a
