### ISSUE TITLE
I added compatibility with Exchange 2013 SP1 CU16

### ISSUE THREAD

**Issue by maximallist** [Pro/dkim-exchange#180]
### Versions

- **Windows Server Version**: 2008 R2 x64
- **Exchange Version**: 2013 SP1 CU16
- **Installed DKIM Exchange Version**: 3.0.9

### Description
Hi, Pro! I ask you to accept changes in the project for support of compatibility with Exchange 2013 CU16. My "Pull requests" #179. Testing took place successfully in my system.
#

**Comment by Pro** [comment]
Thanks a lot!
I'll release it shortly
