### ISSUE TITLE
When Exchange 2016 CU6 Support will be avaliable?

### ISSUE THREAD

**Issue by Bolderus** [Pro/dkim-exchange#184]
Dear Master,

When Exchange 2016 CU6 support will be added?

**Comment by Bolderus** [comment]
Anybody knows when Exchange 2016 CU6 support will be avaliable

**Comment by jaapwess** [comment]
I don't know when CU6 is officially supported, but DKIM signing works flawlessly with CU6

**Comment by Bolderus** [comment]
![dkim_agent](https://user-images.githubusercontent.com/28384123/29552134-af16344a-871e-11e7-8542-61d19fb1aec4.jpg)

But I am getting error when I want to setup.

**Comment by GodfatherX64** [comment]
+1 @Bolderus , i get the same error and cant setup it

**Comment by PermaGreenCLM** [comment]
Try this build, compiled/passed check: #189 
includes Exchange 2013 SP1 CU17  and Exchange 2016 CU6 support

**Comment by leungda** [comment]
where can I download the 3.0.11?

**Comment by AlexLaroche** [comment]
Support since version 3.0.12.
