### ISSUE TITLE
Exchange 2013 CU18

### ISSUE THREAD

**Issue by CrashTheGreat** [Pro/dkim-exchange#193]
Hi!

You have plans to make support CU18? When?

Thanks!

**Comment by reqlez** [comment]
I'm going to try to pickup the slack on at least getting new versions supported, unfortunately I haven't touched an IDE in 10 years... Just installed Visual Studio 2017 and will see how I make out :)  pro does not have a lot of time to work on the project it seems.

**Comment by reqlez** [comment]
Got a request going to merge my code into master, but if you need it right away, you can use the new complied files under my branch: https://github.com/reqlez/dkim-exchange/tree/reqlez-2013CU18

You can clone and install manually. Tested against my CU18 ex2013 server, signed the e-mail just fine nothing crashed.

**Comment by AlexLaroche** [comment]
Resolve by version : v3.0.11

https://github.com/Pro/dkim-exchange/releases/tag/v3.0.11
