### ISSUE TITLE
How to get the Verification to work

### ISSUE THREAD

**Issue by ulfmerbold** [Pro/dkim-exchange#194]
### Versions

- **Windows Server Version**: 2012R2
- **Exchange Version**: 2016 Enterprise CU7
- **Installed DKIM Exchange Version**: selfcompiled 4.0.0 with Verification

### Description

Loaded the Sources, modded to run against Exchange 2016 CU7
Updated Project to MimeKit.1.18.1 and NUnit.2.6.4

But how to get the verification to work?
In the installer script the verification Agent is missing...or im blind...

Help :)

### Steps to Reproduce

not applicable

**Comment by ulfmerbold** [comment]
`# Setup DKIMVerifying
write-host "Registering verifying-agent" -f "red"

Install-TransportAgent -Name "Exchange DkimVerifier" -TransportAgentFactory "Exchange.DkimVerificator.DkimVerificatorAgentFactory" -AssemblyPath "$EXDIR\Exchange.DkimVerificator.dll"

write-host "Enabling verifying-agent" -f "green"
enable-transportagent -Identity "Exchange DkimVerifier"
get-transportagent`

----------------------------------------
my try to get it work, but any hints which state the verification part of the Project has?
be a bit more like a chicken to test it on my productive system

**Comment by Pro** [comment]
The agent currently does not support verifying DKIM signatures. I started implementig it in https://github.com/Pro/dkim-exchange/tree/feature/dkim-verify but did not have time to finish it.
It will also not be included in the near future
