### ISSUE TITLE
Support for Exchange 2016 CU6 & 7

### ISSUE THREAD

**Issue by dwerdler** [Pro/dkim-exchange#196]
Hi There,

First i want to say i'am a fan of this piece of software it really helps us out alot! Cheers for the contributors. Is there any roadmap on when the newest version will be released that supports 2016 CU6 and/or 7?

I saw a post where they are pointing to a checkout of the newest version, but i'am a newbee and don't know how to pull that off! (https://github.com/Pro/dkim-exchange/issues/184).

Hopefully you guys can give me a date or maybe point me in the right direction te get the version mentioned in the link above..

Thanks in advance.

Kind regards,

Danny

**Comment by leungda** [comment]
I am wanting to have support on Exchange 2016 CU6

**Comment by reqlez** [comment]
I'll be adding support for CU6 and CU7 tomorrow ( if somebody doesn't beat me to it lol)

**Comment by AlexLaroche** [comment]
Support since version 3.0.12.
