### ISSUE TITLE
Message body signed incorrectly when MIME file name is too long

### ISSUE THREAD

**Issue by PaulSD** [Pro/dkim-exchange#205]
### Versions

- **Windows Server Version**: 2016
- **Exchange Version**: 2016 CU8 (15.1.1415.2)
- **Installed DKIM Exchange Version**: 3.0.13

### Description

dkim-exchange produces an invalid body signature (gmail, OpenDKIM, and Cisco IronPorts all report it as invalid) for the following test message:
```
From: ...
To: ...
Subject: test
Content-Type: multipart/related;
	boundary="boundary";
	type="multipart/alternative"
MIME-Version: 1.0

--boundary
Content-Type: image/png;
	name="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZab.png"
Content-Description: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZab.png
Content-Disposition: inline;
        filename="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZab.png"

testing

--boundary--
```

Using any filename <= 57 characters seems to work, but any filename >= 58 characters causes an invalid signature.  (The above filename is 58 characters.)
If I leave any of the MIME Content-Type/Content-Description/Content-Disposition headers out or enter inconsistent filenames in them, something (Exchange? MimeKit?) rewrites/creates them such that the filenames match as shown above.  However, if the headers are used as shown above, they seem to be passed through to the receiver with no modifications.

I'm guessing https://github.com/Pro/dkim-exchange/issues/113#issuecomment-280583843 and https://github.com/Pro/dkim-exchange/issues/150 may be related to this issue.

It looks like https://github.com/jstedfast/MimeKit/issues/236 and https://github.com/jstedfast/MimeKit/issues/291 might also be relevant.  Note that the Content-Description line reaches 78 characters when the filename reaches 57 characters.  I wonder if MimeKit is RFC2231 (or RFC2047) encoding that line when calculating the DKIM signature, but is passing through the original line instead of the encoded line when the message is streamed out by the message.WriteTo() call?

**Comment by PaulSD** [comment]
It looks like https://github.com/jstedfast/MimeKit/issues/236 may be relevant ... Perhaps MimeKit is RFC2047 encoding the Content-Description header when generating the DKIM signature, but dkim-exchange is not keeping the encoded version of the body produced/used by MimeKit?

**Comment by jstedfast** [comment]
Hmmm, it's possible that @PaulSD 's guess is correct, but that would suggest that different `FormatOptions` are being used when signing and WriteTo().

Looking at https://github.com/Pro/dkim-exchange/blob/master/Src/Exchange.DkimSigner/DkimSigner.cs#L179, it looks like the default `FormatOptions` are used in both cases, however, it *looks like* the code passes the raw MimeMessage stream back to the Exchange APIs which may or may not choose to use a different encoding when sending the message.

I would recommend modifying this function to write the raw signed message to a temp file and then comparing that to the message that is actually sent out by the Exchange APIs (either by looking at the raw message received by the recipient or by somehow having Exchange dump the message stream to another temp file when it sends it).

My *guess* is that Exchange is formatting the message differently than MimeKit is when sending it.

i.e. MimeKit folds long headers while Exchange does not?

**Comment by jstedfast** [comment]
Looking at the sample message text in the original comment, I couldn't help but notice that there is no `Content-Transfer-Encoding` specified.

This could be the source of the problem as well (unless the image/png attachment really does simply contain the content `testing`).

You might want to "prepare" the message for signing by doing:

```csharp
message.Prepare (EncodingConstraint.SevenBit);
```

This forces MimeKit to examine all of the mime parts and make sure that their encodings are suitable for 7bit transfer (e.g. over SMTP). If your SMTP server supports 8bit encoding, you can use `EncodingConstraint.EightBit` instead.

**Comment by PaulSD** [comment]
The message that goes into exchange and the message that comes out of exchange are identical (confirmed via a hexdump of tcpdump data) ... but maybe MimeKit is folding the header, then Exchange is unfolding it?  I'll see if I can find a way to get a copy of the raw message after it is signed by MimeKit and before it is sent back to Exchange...

Adding a `Content-Transfer-Encoding` header doesn't seem to make any difference.  The sample message above was a minimal test case that I developed by trial-and-error, so the image/png attachment actually does include only `testing` in this case (the data in the attachment doesn't seem relevant to this issue).

**Comment by PaulSD** [comment]
For what it's worth, running the following code to sign my above test message directly using MimeKit seems to generate a valid signature and does not modify the body in any way:
```
var message = MimeMessage.Load("message.unsigned");
var headers = new HeaderId[] { HeaderId.From, HeaderId.Subject };
var headerAlgorithm = DkimCanonicalizationAlgorithm.Simple;
var bodyAlgorithm = DkimCanonicalizationAlgorithm.Simple;
var signer = new DkimSigner("key", "example.com", "test") {
    SignatureAlgorithm = DkimSignatureAlgorithm.RsaSha256,
    QueryMethod = "dns/txt",
};
message.Sign (signer, headers, headerAlgorithm, bodyAlgorithm);
message.WriteTo(FormatOptions.Default, "message.signed");
```

**Comment by PaulSD** [comment]
I haven't been able to find any way to prevent `mailItem.GetMimeWriteStream().WriteTo()` from unwrapping the Content-Description ... `mailItem.Message.Normalize()` seems to erase the whole message body.

So the only solution seems to be to have MimeDocument reformat the message before signing.

**Comment by jstedfast** [comment]
Awesome, glad you found a solution!
