### ISSUE TITLE
No password finder specified, but a password is required

### ISSUE THREAD

**Issue by snbx64** [Pro/dkim-exchange#209]
### Versions

- **Windows Server Version**: [2012]
- **Exchange Version**: [2013]
- **Installed DKIM Exchange Version**: [3.0.13]

### Description
I am trying to specify a password protected private key file.  When I try this I receive the error:-
No password finder specified, but a password is required
Presumably from bouncycastle.dll
https://github.com/kerryjiang/BouncyCastle.Crypto/blob/master/Crypto/openssl/PEMReader.cs
### Steps to Reproduce

1. Create a password file using puttygen and assign it file a password
2. Using puttygen conversion export the private key
3. This private key will have the password of the ppk file
Alternatively create the private key using dkim signer and use openssl to assign a password
openssl rsa -in in.pem -out out.pem des
this should prompt for a password for out.pem
then try to load this private key

**Expected behavior:** [Be prompted for the private key password, as the private key is being stored on the server]

**Actual behavior:** [error:No password finder specified, but a password is required]

**Comment by snbx64** [comment]
Has anyone else had this issue or are you using non password protected private keys ?

**Comment by AlexLaroche** [comment]
We are using non password protected private keys. You don't have any extra protection when your encrypt your private key if the password for decrypt it is in clear text.

**Comment by Pro** [comment]
Private keys with password are not supported and also do not make much sense for the signer.
