### ISSUE TITLE
Cannot install on Exchange 2013 SP1 CU15

### ISSUE THREAD

**Issue by dhirsch3D** [Pro/dkim-exchange#210]
### Versions

- **Windows Server Version**: Server 2012 R2 Standard
- **Exchange Version**: Exchange 2013 SP1 CU15 (15.0.1263.5)
- **Installed DKIM Exchange Version**: 3.0.13

### Description

When I attempt to install the software using the normal method, it claims to install successfully, but doesn't actually sign anything.  When I use the fully manual PowerShell method, I get these errors: 

```
Registering agent
The TransportAgentFactory type "Exchange.DkimSigner.DkimSigningRoutingAgentFactory" doesn't exist. The
TransportAgentFactory type must be the Microsoft .NET class type of the transport agent factory.
Parameter name: TransportAgentFactory
    + CategoryInfo          : InvalidArgument: (:) [Install-TransportAgent], ArgumentException
    + FullyQualifiedErrorId : [Server=EXCH01,RequestId=1a45ee4f-6be7-4bf5-8905-abecbfaf71ae,TimeStamp=2/21/2018 5:12:0
   8 PM] [FailureCategory=Cmdlet-ArgumentException] 2C23DBB3,Microsoft.Exchange.Management.AgentTasks.InstallTranspor
  tAgent
    + PSComputerName        : exch01.fec.local

Enabling agent
Transport agent "Exchange DkimSigner" isn't found.
Parameter name: Identity
    + CategoryInfo          : InvalidArgument: (:) [Enable-TransportAgent], ArgumentException
    + FullyQualifiedErrorId : [Server=EXCH01,RequestId=ab158898-d703-4185-a0e9-9bd2e5877520,TimeStamp=2/21/2018 5:12:0
   8 PM] [FailureCategory=Cmdlet-ArgumentException] 2D5F276A,Microsoft.Exchange.Management.AgentTasks.EnableTransport
  Agent
    + PSComputerName        : exch01.fec.local
```

I've seen similar errors reported for earlier versions of Exchange, but not for CU15.  Any help or suggestions would be appreciated!

-Dave

**Comment by o-eazy** [comment]
Dave these links might be helpful:
https://github.com/Pro/dkim-exchange/issues/24

https://support.microsoft.com/en-us/help/2938053/third-party-transport-agents-cannot-be-loaded-correctly-in-exchange-se

**Comment by dhirsch3D** [comment]
Unfortunately, that issue was fixed in CU5; I'm at CU13.  Nevertheless, I did try the fix: no luck.

**Comment by Pro** [comment]
Make sure that the powershell command in the install script succeeds:

```
$EXDIR="C:\Program Files\Exchange DkimSigner"
Install-TransportAgent -Name "Exchange DkimSigner" -TransportAgentFactory "Exchange.DkimSigner.DkimSigningRoutingAgentFactory" -AssemblyPath "$EXDIR\ExchangeDkimSigner.dll"
```

And also make sure that the .dll is at the right place
