### ISSUE TITLE
Exchange Server 2013 CU20

### ISSUE THREAD

**Issue by davidenco** [Pro/dkim-exchange#216]
Can you add support for Exchange Server 2013 CU20 please?

**Comment by davidenco** [comment]
???

**Comment by mr-flibble** [comment]
@davidenco Hello, you can help with that if you have Exchange 2013 CU20 installed
https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md#how-to-include-support-for-newer-exchange-versions

Like this:
https://github.com/Pro/dkim-exchange/pull/169

**Comment by davidenco** [comment]
OK done, see: #219

**Comment by davidenco** [comment]
Is anyone able to build the latest pull request I have submitted? I am not experienced with Visual Studio or C# but still tried to build the project in VS and it failed.

**Comment by mr-flibble** [comment]
Can anyone please confirm pull request #219 ? CU20 was released 70 days ago :(
Thanks

**Comment by davidenco** [comment]
I have actually given up and been using the current version with CU20 and had no problems whatsoever.

**Comment by mr-flibble** [comment]
Thanks for info, so latest version 3.0.13.0 is (for CU19) is working fine with CU20 ?
I now deciding if I should wait more, or go for CU19

**Comment by davidenco** [comment]
Yes, version 3.0.13 works fine with Exchange version 15.0.1367.3 (CU20).

**Comment by Pro** [comment]
@davidenco thanks for all your help!!!
I will try to release 3.1 today which includes the new version
