### ISSUE TITLE
2016 CU9 Support

### ISSUE THREAD

**Issue by aledr** [Pro/dkim-exchange#218]
Hi!

Can you add support for this release?

Thanks.

**Comment by belykhk** [comment]
Actually CU8 version is compatible with CU9, just tested myself
To install dkim-exchange on 2016 CU9 you need 
1) edit install.ps1 and add this code before "The exchange version is not yet supported:" part:
```
elseif (($exchserver.admindisplayversion).major -eq 15 -and ($exchserver.admindisplayversion).minor -eq 1 -and ($exchserver.admindisplayversion).build -eq 1466) {
	$EXVER="Exchange 2016 CU9"
}
```
2)Copy folder _dkim-exchange-3.0.13\Src\Exchange.DkimSigner\bin\Exchange 2016 CU8_ to _dkim-exchange-3.0.13\Src\Exchange.DkimSigner\bin\Exchange 2016 CU9_

It's not good workaround, but better than nothing

**Comment by aledr** [comment]
Thanks!

**Comment by Pro** [comment]
Done in new release 3.1
