### ISSUE TITLE
DKIM Verificator branch - DKIM verification will fail when using GetMimeReadStream from MailItem

### ISSUE THREAD

**Issue by rbfajardo** [Pro/dkim-exchange#220]
### Versions

- **Windows Server Version**: N/A
- **Exchange Version**: Exchange 2016 (Any CU)
- **Installed DKIM Exchange Version**: DKIM-Verify branch

### Description

DKIM verification will fail in MimeKit when using GetMimeReadStream from MailItem. This happens because exchange will convert or fix up the content of the mime message when calling GetMimeReadStream. Body Hash will not match the original Body Hash in the DKIM signature.

### Suggested edit

Sample code:
```
            MimeMessage mimeKitMessage = null;
            StringBuilder builder = new StringBuilder();

            MemoryStream streamHeaders = new MemoryStream();
            Microsoft.Exchange.Data.Mime.EncodingOptions options = new Microsoft.Exchange.Data.Mime.EncodingOptions("US-ASCII", "en-US", Microsoft.Exchange.Data.Mime.EncodingFlags.None);

            // Get the raw message headers and convert to text/string
            mailItem.Message.RootPart.Headers.WriteTo(streamHeaders, options);
            string headerText = StreamToString(streamHeaders);
            builder.Append(headerText);

            builder.AppendLine("");

            // Get the raw message body and convert to text string
            Stream streamBody = new MemoryStream();
            streamBody = mailItem.Message.MimeDocument.RootPart.GetRawContentReadStream();
            string bodyText = StreamToString(streamBody);
            builder.Append(bodyText);

            // Merge headers and body to string
            string eml = builder.ToString();

            mimeKitMessage = MimeMessage.Load(StringToStream(eml), true);
```

**Expected behavior:** DKIM verify should be true.

**Actual behavior:** DKIM verify is false when using GetMimeReadStream from MailItem. Pass the raw message instead so that DKIM verification passes.

**Comment by Pro** [comment]
@rbfajardo first of all thanks for your help.
Verifying is currently not fully implemented, but maybe with your help we can get it up and running. Could you create a Pull Request for your changes?

**Comment by rbfajardo** [comment]
Happy to help, I have not visited this in a while but will work on this soon.

**Comment by rbfajardo** [comment]
Created a pull request #227 but not sure why it did not pass. @Pro Can you review?

**Comment by gbusoni** [comment]
has verificator ever reached a release version? Or still under development?

**Comment by rbfajardo** [comment]
@gbusoni This never went anywhere. Happy to help contribute though. I am going to close this for now.
