### ISSUE TITLE
Not an Issue More of an Install Query

### ISSUE THREAD

**Issue by RichieRogers** [Pro/dkim-exchange#221]
Hi,
Looking to install this on my Exchange 2016 environment, but I have a query relating to multiple servers.
In my environment I have two Exchange Servers in a DAG. 
Do I need to install this on one or both servers?
If both, do I need to do anything different on the second server like copying config over from first server?

Thanks in advance for any help,
Richie

**Comment by rbfajardo** [comment]
Yes, you need to install it on all transport servers sending outbound emails. You will need to copy over your config and private signing keys.

**Comment by RichieRogers** [comment]
Thanks for confirming.

Richie
