### ISSUE TITLE
Can't check available version of dkim-exchange

### ISSUE THREAD

**Issue by unik-web** [Pro/dkim-exchange#224]
### Versions

- **Windows Server Version**: Windows Server 2012 R2
- **Exchange Version**: Exchange server 2013
- **Installed DKIM Exchange Version**: 3.0.12

### Description

Can't check available version of dkim-signer. Get this error message "Couldn't get current version.
Check your Internet connection or restart the application."

**Comment by ModernAesthetics** [comment]
I get this as well

**Comment by unik-web** [comment]
rbfajardo thanks for help. I fixed this issue

**Comment by viorelovidiu** [comment]
Hello, recompiled download link not working anymore. Can be uploaded again?
Thanks!

**Comment by Pro** [comment]
Duplicate of #198. Will be fixed in newest version released soon

**Comment by havanazzz** [comment]
Hello, Im pretty sure i have Exchnage 2013 U20 installed but Getting Error

Your Microsoft Exchange version isn't supported by the DKIM agent: 15.0.1395.4

Can someone help?

**Comment by jamilnoc** [comment]
> Use the fixed version here: #198

can you send me fixed version please? because link down
