### ISSUE TITLE
[fiddler] 0x80090302 调用 SSPI 失败，请参见内部异常。 < 要求的函数不受支持

### ISSUE THREAD

**Issue by BitmapLong** [Pro/dkim-exchange#225]
** LogString: fiddler.network.https> HTTPS handshake to api.huobi.pro (for #11) failed. System.Security.Authentication.AuthenticationException 调用 SSPI 失败，请参见内部异常。 < 要求的函数不受支持

Win32 (SChannel) Native Error Code: 0x80090302
Error
基础连接已经关闭: 发送时发生错误。

**Comment by mr-flibble** [comment]
I think this can be similar to https://github.com/Pro/dkim-exchange/issues/198

**Comment by Pro** [comment]
Duplicate of #198
