### ISSUE TITLE
Exchange 2013 SP1 CU21

### ISSUE THREAD

**Issue by davidenco** [Pro/dkim-exchange#233]
Please see pull request #232.

**Comment by mr-flibble** [comment]
Any progress on this please?
This month we are lucky - CU20 [was security patched](https://support.microsoft.com/en-us/help/4340731/description-of-the-security-update-for-microsoft-exchange-server-2013), but next month we do not have to be so lucky.
MS stated that only CU21 will be supported.

**Comment by wish01** [comment]
When will the stable version with CU21 support come out?

**Comment by sulzer** [comment]
+1 

Although it says in the readme that the project is not actively maintained, so unless someone else steps in we can't really expect anything.

**Comment by davidenco** [comment]
FYI, the current version works fine with CU21.

**Comment by RickStinson** [comment]
so you mean Version 3.1.0 works with CU21 without updating any files?

**Comment by davidenco** [comment]
Correct. It does for me anyway.

**Comment by RickStinson** [comment]
very cool, thanks, i will try it on the weekend!

**Comment by havanazzz** [comment]
doesnt work for me.. version is 15.0.1395.4 for U21 not supported

**Comment by imasonaz** [comment]
I can confirm from a fresh install that v15.1395.4 will not install on CU21.

@davidenco can you give any updates or insight with this?

**Comment by RickStinson** [comment]
Hi,
i'm not a coder and i have no idea using github right, but i installed visual studio and added support for Exchange 2016 CU11 and Exchange 2013 CU21.

its untested, but you can download it here und install it with install.ps1 powershell script
https://github.com/RickStinson/dkim-exchange/tree/exch2016cu11

**Comment by imasonaz** [comment]
@Pro could you merge this commit, please?

**Comment by nwiegerinck** [comment]
@RickStinson unfortunately its not working on my server: "Couldn't determine installed Exchange Version: Couldn't initialize Powershell runspace". Any ideas?

**Comment by salimagic** [comment]
So, I grabbed the Ninja101 installer of this. Every time I open to install DKIMSigner, it just automatically downloads the 3.1 version from this post. How do I change where it's grabbing the files from?

**Comment by caffari** [comment]
> So, I grabbed the Ninja101 installer of this. Every time I open to install DKIMSigner, it just automatically downloads the 3.1 version from this post. How do I change where it's grabbing the files from?

You need to follow the instructions for a manual install.  The installer only downloads from the pro/ account.  You will want to download the pkg from the Ninja101/ account
https://github.com/Ninja101/dkim-exchange
