### ISSUE TITLE
Null

### ISSUE THREAD

**Issue by mythumbsclick** [Pro/dkim-exchange#237]
Hi

I just have simple quick questions

1. How does dkim-exchange work with From addresses? Does it look at RFC5321.MailFrom or RFC5322.From. The reason I ask is I want to DKIM sign Exchange Out Of Office messages (and other Exchange generated emails) that have a null RFC5321.MailFrom address.  Will dkim-exchange sign them using the RFC5322.From?
2. Will this work with Exchange 2013 SP1 CU21?

Many thanks

**Comment by mr-flibble** [comment]
Hello, 

2.
CU21 is not yet supported - only CU20
CU21 is waiting in pull requests https://github.com/Pro/dkim-exchange/pulls

**Comment by rbfajardo** [comment]
I realize this is an old question but wanted to post an answer anyway. DKIM-Exchange is looking at the P2 from address.

This issue can be closed.

        private void SignMailItem(MailItem mailItem)
        {
            // If the mail item is a "system message" then it will be read-only here,
            // and we can't sign it. Additionally, if the message has a "TnefPart",
            // then it is in a proprietary format used by Outlook and Exchange Server,
            // which means we shouldn't bother signing it.
            if (!mailItem.Message.IsSystemMessage && mailItem.Message.TnefPart == null)
            {
                string domainPart = null;
                
                /* Check if we have a valid From address */
                if (!mailItem.FromAddress.IsValid || mailItem.FromAddress.DomainPart == null)

**Comment by DJBenson** [comment]
Answered by @rbfajardo above (and historic topic) - closing.
