### ISSUE TITLE
Option not to sign message body?

### ISSUE THREAD

**Issue by Thompson-1** [Pro/dkim-exchange#240]
### Versions

- **Windows Server Version**: Server 2016
- **Exchange Version**: 2016, CU9
- **Installed DKIM Exchange Version**: 3.10

### Description

I keep getting wrong body hash failures on all emails. I think this may be due to all our emails being sends via Mimecast spam filter, which maybe messes it up.

Using DKIM Manager for IIS SMTP and Exchange Server, I can get it to work if I enable option:
Sign a part of the message and set Maximum length of message body to sign to 0 bytes.

Is there any similar option in Exchange DKIM Signer?

### Steps to Reproduce

1. Install and configure Exchange DKIM Signer using default options add external DNS record.
2. Do a test

**Comment by Thompson-1** [comment]
Anyone got any ideas?

here's the result form a test. I set DKIM to only sign the subject but it's still failing:

DKIM-Signature: v=1; a=rsa-sha256; d=dhc.bc.ca; s=s607; c=relaxed/relaxed;
	t=1539618846; h=subject:from;
	bh=4G8QNx2wHDUN8i+4zDJOMubrUv4Wddvkev299TOgNdc=;
	b=Wl9EP2ubT9yDE3GKZg0W+JD3MvQVrBjMd09zkeLOkWcsK9alp2Fds1Vcxqjt8UlJoWdCQSb6Qwl
	I/o+0roEYjiug705wsoccW6KtI5/TInszNbKEy4XEqUK2VXoFttlxvFKCc50w8n6qVPxwSB+dtcXH
	yqL+LV4Dv4+/VvtafM4=
Signed-by: Miles.Thompson@...
Expected-Body-Hash: 9ujzkK4Y7zByi/TcKnmv6GxrjIEGNG10XJO5qQqFqIw=

DKIM-Result: fail (wrong body hash: 4G8QNx2wHDUN8i+4zDJOMubrUv4Wddvkev299TOgNdc=)

**Comment by harrijon** [comment]
I am having the same issue: Body Hash Did Not Verify

..any advice would be greatly appreciated..

Windows Server Version: Server 2019
Exchange Version: 2016, CU10
Installed DKIM Exchange Version: 3.1.0

**Comment by harrijon** [comment]
> @harrijon I found out in the end that our spam filtering service (mimecast) did DKIM signing at their end, so got it setup there instead of on the Exchange server.

ok, thx @Thompson-1
