### ISSUE TITLE
I would love to Help!

### ISSUE THREAD

**Issue by shavrasho** [Pro/dkim-exchange#244]
Hallo Pro,

I'm would like to help maintain dkim-exchange for new 2013/2016 CUs and then help add additional features and support for 2019 with future updates.
My Visual Studio skills are good, also I'm a programmer & Systems engineerso i will be able to test newer releases further also quicker support.

**Comment by dniakamal** [comment]
Check out CONTRIBUTING.md https://github.com/Pro/dkim-exchange/blob/master/CONTRIBUTING.md for more info.

**Comment by luxzg** [comment]
Is there a professional coder that can issue a valid invoice that we can "reward" for contributing new updates for Exchange 2016 CUs? This offer is also open to the project maintainer. If we can expect new CUs of 2016 supported, and get a valid invoice, we would rather support this project then go with other DKIM signing solutions for Exchange. At very least general public would have the same benefits. We did a "hack" of CU10 to CU11 on test server and seems to work without issues, but simply reusing dlls from old CU doesn't sound like a solution for production or any long term deployment. Please post a reply if interested.

**Comment by shavrasho** [comment]
Sure! Please contact me!

**Comment by luxzg** [comment]
Mail or link to website? Thanks!

**Comment by shavrasho** [comment]
omar@omarino.de

**Comment by luxzg** [comment]
Sent to email to both @Pro and @shavrasho

**Comment by Pro** [comment]
I am happy if someone is willing to maintain the project further (I also don't mind if someone is getting paid for that!). I'm really sorry that I don't have more time to support this further.

The general process is:

1. Create a few PRs which I can review. also mention there that you would like to maintain the project in the future.
2. After I see that the PRs are apropriate quality, I will add that person as maintainer to the project, so he/she can directly push/release

**Comment by luxzg** [comment]
Sounds reasonable to me. Let me know how it goes. Also, there's that PR for 2016 CU11 that  @dniakamal was kind to provide. Thank you all!

**Comment by DJBenson** [comment]
Closing as I am have been made collaborator on the project and will be taking the project forward. Will still need support from the community but regular releases should now be available to everybody again.
