### ISSUE TITLE
Exchange 2013 CU21 Support

### ISSUE THREAD

**Issue by RappMan** [Pro/dkim-exchange#246]
Can you update the code to provide support for Exchange server 2013 CU21?

- **Windows Server Version**: [Your version]
- **Exchange Version**: [Your version]
- **Installed DKIM Exchange Version**: [Your version]

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by EricLCTCS** [comment]
Any plan to add support for Exchange 2013 CU21?

**Comment by Froschmedia** [comment]
Hello, i need the support for the CU21 too.

**Comment by nwiegerinck** [comment]
Hello, i need the support for the CU21 too...

**Comment by nielsch87** [comment]
me too

**Comment by Julien-nl** [comment]
thank you for this program, i know everybody is doing this in their free time, i hope to see the support of the cu21.
big thank you

**Comment by gorringS** [comment]
I have tried to install from above link that you posted regarding CU21 but appears to not work . Can you provide a link to executable as presently appears only version is 3.1.0 and that not compliant with CU21 presently via website

**Comment by h53q9xfd** [comment]
> 
> 
> I have tried to install from above link that you posted regarding CU21 but appears to not work . Can you provide a link to executable as presently appears only version is 3.1.0 and that not compliant with CU21 presently via website

https://github.com/Ninja101/dkim-exchange/releases/download/v3.1.1/Configuration.DkimSigner.zip

**Comment by gorringS** [comment]
unfortunately when I unzip the proclaim file given via the url in previous reply it was found be only version 3.1.0 sadly this deems it not able used for CU21 . Not sure weither person who sent have verified that copy of zip file is not just renamed copy file found on website. Hopefully his can be sorted resent with correct zip file

**Comment by GokuH12** [comment]
Hi, i went to that repo, and was able to install finally to my Exchange 2013 Sp1 CU21, but u have to go throuht the manual process ( Its seems that the bin wasnt compiled updating the new number of version), and add some folder in the process, so the script can run without problem.
Confirm working here =)

**Comment by gorringS** [comment]
wish mine would work seem when I type cmd in powershell it fails to work far getting script to go

**Comment by gorringS** [comment]
Detecting Exchange version ...
Get-ExchangeServer : The term 'Get-ExchangeServer' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that t
At C:\Users\Administrator\Desktop\dkim-exchange-master\install.ps1:49 char:15
+ $exchserver = Get-ExchangeServer -Identity $hostname
+               ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ExchangeServer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The exchange version is not yet supported:
At C:\Users\Administrator\Desktop\dkim-exchange-master\install.ps1:140 char:2
+     throw "The exchange version is not yet supported: " + $exchserver.admindisplayv ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The exchange ve...yet supported: :String) [], RuntimeException
    + FullyQualifiedErrorId : The exchange version is not yet supported:

**Comment by gorringS** [comment]
that what I get as files that have tired to download not vailded  for C21

**Comment by GokuH12** [comment]
This it's what I did:
Download this: https://github.com/Ninja101/dkim-exchange/archive/v3.1.1.zip

U will get the source code, see the version number. (3.1.1).

Unzip it.
Open the exchange Shell with elevated Rights.
Go to that folder in the shell.
Before going to the install process, u have to go to the folder src/.../bin/ and copy the folder exchange...C20 and paste but, change the name to C21 (Don't have the name folder in the moment).

Now follow the instructions for manual installation and u should be ready to go.

When installed u will see that although it's installed the 3.1.1, this will show 3.1.0, seems that forgot to change some files to update the version, but that it's no problem once installed.

Hope this can guide u a little.

**Comment by gorringS** [comment]
thanks issue is resolved now due those instructions . Seems I was doing everything right but didn't relies had to make copy of the existing folder C20 and change name . Installed completed and working now

**Comment by GokuH12** [comment]
Great! =)
