### ISSUE TITLE
Offline install for DKIM signer

### ISSUE THREAD

**Issue by ahmeds84** [Pro/dkim-exchange#248]
### Versions

- **Windows Server Version**: [Windoes Server 2008 R2]
- **Exchange Version**: [Exchange 2003]
- **Installed DKIM Exchange Version**: [3.1.0]

### Description

Unable to complete offline install. When clicking on 'install' no option to select zip source file, goes straight to download.

### Steps to Reproduce

1. Extract Configuration.DkimSigner to folder on desktop
2. Download dkim-exchange-3.1.0 (source zip) to desktop
3. Opened Configuration.DkimSigner and clicked on 'Install' 

**Expected behavior:** [Ability to browse to source zip]

**Actual behavior:** [No option to select/browse to source zip is presented]

**Comment by salimagic** [comment]
I'm experiencing the same exact issue :(

**Comment by caffari** [comment]
You have to do manual install
