### ISSUE TITLE
DKIM Body Hash Did Not Verify

### ISSUE THREAD

**Issue by harrijon** [Pro/dkim-exchange#252]
### Versions

- **Windows Server Version**: 2019
- **Exchange Version**: 2016 CU10
- **Installed DKIM Exchange Version**: 3.1.0

### Description

DKIM Body Hash Did Not Verify

I am not an expert.  And I can't figure out why this is not working.  I don't know if I am missing a setting or what.  I've been googling and rummaging through github issues for days/hours trying to figure this out.

Any help would be greatly appreciated.

The issue is on a new windows 2019 server.  Previously, we had dkim signer working correctly for years on old win 2008 r2 -exchange 2010 server.  

DNS records are setup correctly and align correctly according to all validators that I've tried: mx toolbox, port25, dkimvalidator, etc.

Exchange DkimSigner is the last transport agent in the list. Get-TransportAgent

I've tried many, if not all combinations of sha1, sha256, simple, relaxed.  All to no avail.

### Steps to Reproduce

1. send email to: ping@tools.mxtoolbox.com
2. go to https://mxtoolbox.com/deliverability/ and submit email address it was sent from

ref: https://mxtoolbox.com/deliverability/52ea9dcb-a105-4f14-8719-4b57ceb17a19

**Expected behavior:** 

Hash the body correctly.

**Actual behavior:** 

Body not hashed correctly.

**Comment by Rgudk0v** [comment]
Hi!
The same problem.
Exchange DkimSigner is the last one in Get-TransportAgent.
And here is my investigation conclusion: this error exist only when i send **.eml or .mes** as an attachment.

Empty message - no error.
Just text in a body - no error.
XLSX, DOCX, TXT or whatever - no error.

As soon, as I attach **.em**l files to message error appears:
 dkim=neutral (_**body hash did not verify**_) header.i=@mydomain.org header.s=mail header.b=beWaKxX+;

About my Environment.
Exchange Server 2016 Cumulative Update 8.
Anti-Spam agents installed and enabled.
Exchange faced the internet directly.
DKIM Signer: 3.1.0 (latest)

**Comment by harrijon** [comment]
My original problem was fixed.  It was not associated with this software, but instead with the dkim tester.

It turns out that mxtoolbox.com had a problem with their dkim analyzer.  They fixed it. https://mxtoolbox.com/deliverability/ 

Here is another reputable dkim tester: https://dkimvalidator.com/

**Comment by harrijon** [comment]
@Rgudk0v do the attached .eml files have dkim headers inside them?  ..could that be triggering the error?

**Comment by caffari** [comment]
Is there any particular reason why you are signing the body as well? I only sign the main header fields (From, To, Date, Subject & MessageID)

Some corporate email servers append inline text to the bottom of incoming emails before they are parsed by anti-spam agents.  In situations like that, the body hash would be invalidated. I'm not sure this would make a difference in your case. I'm just curious as to why you need to include the body. The existing header fields are quite unique as they are, especially with the MessageID header.

**Comment by harrijon** [comment]
@caffari : our dkim signer settings only sign these fields: From, To, Date, Subject.  We removed "MessageID."  "Body" is not an option.

But, mxtoolbox was reporting a problem with signing the body.   That issue has been fixed on the mxtoolbox.com side.

I believe my original problem has been resolved.

**Comment by caffari** [comment]
@harrijon Understood. Thanks for clarifying.
