### ISSUE TITLE
Exchange 2013 CU22

### ISSUE THREAD

**Issue by caffari** [Pro/dkim-exchange#256]
### Versions

- **Windows Server Version**: 2012 R2
- **Exchange Version**: 15.0.1395.4
- **Installed DKIM Exchange Version**: 2013 CU21 (3.1.0 but supposed to be 3.1.1)

### Description

This is not really a bug but rather an issue of a missing src folder for 2013 CU21.

I few weeks ago did a manual install for CU21 from Ninja100 fork, but the pkg did not have a src folder for CU21, so based on instructions I found here I just replicated the CU20 folder.

Since then Ninja101 released 3.2.0 with support for 2013 CU22 and replaced the src folder for CU20 stating that it was a bad build. This means I am currently running the bad build.

So, now in order to replace my install with the latest build, the CU21 src folder is still missing from the download. The question now is: Do I replicate the CU20 src folder (3.1.0 dll) or the CU22 src folder (3.2.0 dll)?

**Comment by Ninja101** [comment]
Can you try the latest pre-release?
