### ISSUE TITLE
dkim=fail (body hash did not verify)

### ISSUE THREAD

**Issue by Rgudk0v** [Pro/dkim-exchange#257]
### Versions

- **Windows Server Version**: Windows Server 2016 STD
- **Exchange Version**: Exchange Server 2016 Cumulative Update 8
- **Installed DKIM Exchange Version**:  3.1.0

### Description

Exchange DkimSigner is the last one in Get-TransportAgent.
And here is my investigation conclusion: this error exists only when I send  .msg as an attachment.

Empty message - no error.
Just text in a body - no error.
XLSX, DOCX, TXT or whatever - no error.

As soon, as I attach .msg files to message error appears:
**Office365:** dkim=fail (body hash did not verify)
**GMAIL:** dkim=neutral (body hash did not verify) header.i=@mydomain.org header.s=mail header.b=beWaKxX+;

Moreover, on the "DKIM Settings" tab I added only: FROM, SUBJECT, TO, DATE. Nothing else.
Tried both: RsaSha1 and RsaSha256, Simple and Relaxed. No luck in any case.

### Steps to Reproduce

-Create a new message;
-add any .msg (in my case it was .msg from the same mailbox from the same server) file as an attachment;
-Send it to any Gmail, or office 365 mailbox.
-See the error

**Expected behavior:** 
DKIM check should PASS

**Actual behavior:** 
DKIM FAILED

**Comment by Ninja101** [comment]
This seems to be a problem with Exchange appending the body of the attached email message after the transport agents have run. Not sure if we can fix this.
