### ISSUE TITLE
Error while installing: 'microsoft.exchange.data.common.dll' already exists

### ISSUE THREAD

**Issue by jterpstra1** [Pro/dkim-exchange#258]
### Versions

- **Windows Server Version**: Windows Server 2012 R2
- **Exchange Version**: Exchange 2016 CU11
- **Installed DKIM Exchange Version**: 3.2.0

### Description

When I try to install DKIM it gives me the error that microsoft.exchange.data.common.dll already exists in Echange 2013 CU20:

![image](https://user-images.githubusercontent.com/49212524/56306936-0c16c500-6144-11e9-8806-1be38a53d101.png)

https://i.imgur.com/FHkxMdx.png

### Steps to Reproduce

1. Open dkim
2. press use pre release
3. hit install

**Expected behavior:** That DKIM would install

**Actual behavior:** It returned an error when trying to install DKIM

**Comment by davidenco** [comment]
Also occurs with the "Upgrade" option.

CU20 and CU22 folders contain duplicate files (same filename, just different case).

**Comment by doomsday201** [comment]
I get the same error, waiting for a decision

**Comment by Ninja101** [comment]
Closing this as was resolved with the new pre-release.
