### ISSUE TITLE
Exchange 2019 - anyone using?

### ISSUE THREAD

**Issue by robatwork** [Pro/dkim-exchange#265]
This is a fantastic project so many thanks to the author and the forks.

I know the latest version has support for Exchange 2019, but before I take the plunge and upgrade my E2016 CU10 server can I just check if anyone is actually using this with E2019 (on 2019 server)?

thanks again
Rob

**Comment by chrisxp0** [comment]
Yeah, I have CU1 and it I get an error saying my versions not supported although in readme it clearly states supported.

**Comment by jclimac** [comment]
Yes, I'm using it on 2019 CU1 and works great.

To be able to install you will need to check the "Include prerelease version", this will enable the version 3.2.0 which is compatible with Exchange 2019.

**Comment by robatwork** [comment]
Thanks both - when I'm feeling braver I'll give it a go

**Comment by chrisxp0** [comment]
I actually ticket the box suggested above and it worked perfect, never realised I needed to.

All good and been running fine for a few days now.

Get Outlook for Android

________________________________
