### ISSUE TITLE
Update for Exchange Server 2016 CU13

### ISSUE THREAD

**Issue by ACPLIT** [Pro/dkim-exchange#268]
Just wondering what the time line is for Exchange 2016 CU 13 Version 15.01.1779.002
Current installer is not compatible and the singer does not install.

**Comment by sawe1900** [comment]
> Just wondering what the time line is for Exchange 2016 CU 13 Version 15.01.1779.002
> Current installer is not compatible and the singer does not install.

Looks like the files are missing within \dkim-exchange-master\Src\Exchange.DkimSigner\bin\ for the install.ps1 to work

**Comment by kefalo1** [comment]
How can you solve the problem with CU13???

**Comment by sarthurdev** [comment]
This is working now, I have re-released the pre-release version of v3.1.0
