### ISSUE TITLE
Exchange 2019 CU2

### ISSUE THREAD

**Issue by EAGCTX** [Pro/dkim-exchange#271]
### Versions

- **Windows Server Version**: 2019
- **Exchange Version**: 2019 CU@
- **Installed DKIM Exchange Version**: 3.2

While I actually did get 3.2 working on my Exchange 2019 CU2 server, I did run into some error messages while installing it.
Just wondering if "official" support is going to be added.

**Comment by sarthurdev** [comment]
I have added CU2 to the master branch, though I do not have Exchange 2019 to test it. It'll be added to a release when tested.

You can install it now by following the manual install instructions, though instead of downloading the release, download a zip of the master branch.
