### ISSUE TITLE
Exchange 2013 CU23

### ISSUE THREAD

**Issue by hello-polosaty** [Pro/dkim-exchange#272]
DKIM is not installed on the Exchange server 2013 CU23. Agent - v3.2.0 (2019-04-18)

**Comment by stdub7** [comment]
> DKIM is not installed on the Exchange server 2013 CU23. Agent - v3.2.0 (2019-04-18)

Works fine
![2019-08-05_081119](https://user-images.githubusercontent.com/53290364/62440512-2d360c80-b759-11e9-9e5b-c9b73ad54b28.png)

**Comment by hello-polosaty** [comment]
What can i do wrong. I downloaded - https://github.com/Pro/dkim-exchange/releases/tag/v3.1.0, chose - Include prerelease version. got an error.

![image](https://user-images.githubusercontent.com/41310347/62615527-1be62f00-b916-11e9-9ccc-df7d97828aec.png)

**Comment by stdub7** [comment]
Use master branch
https://github.com/Pro/dkim-exchange/archive/master.zip

**Comment by pvdijk01** [comment]
Used the master branch (https://github.com/Pro/dkim-exchange/archive/master.zip) , selected "include prerelease versions" but still no succes.

**Comment by sarthurdev** [comment]
I have re-released the pre-release of v3.1.0 - does it work for you now?

**Comment by pvdijk01** [comment]
Thx, i will try that tomorrow!
Ill get back to you with the results.


Op do 29 aug. 2019 15:43 schreef Simon <notifications@github.com>:

**Comment by pvdijk01** [comment]
Thx sarthurdev, this 3.2.0. version works!
