### ISSUE TITLE
Read Recipient not signed

### ISSUE THREAD

**Issue by joskeatwork** [Pro/dkim-exchange#273]
### Versions

Windows Server Version: 2012 R2
Exchange Version: 15.00.1365.001
Installed DKIM Exchange Version: 3.2.0

### Description

System message are not DKIM signed
More specific: read recipient

### Tried

Set-RemoteDomain -Identity * -TNEFEnabled:$False
--> No change in behaviour

**Comment by sarthurdev** [comment]
If memory serves, this isn't possible due to system messages being read-only to the transport agent.

**Comment by Deckard99** [comment]
Hi,

I just came across the same problem. I do have multiple servers with DKIM Signer, where read receipts are getting signed and installed another server lately where it wouldn't sign those messages. Where there versions that made it possible to sign read receipts? I just tested again and read receipts from my business mailbox are always signed. Using Edge 2016 on Windows 2012R2.
