### ISSUE TITLE
Installer incorrectly identifies unsupported version

### ISSUE THREAD

**Issue by MRRamsay** [Pro/dkim-exchange#277]
### Versions

- **Windows Server Version**: Server 2016
- **Exchange Version**: 15.1.1531.3
- **Installed DKIM Exchange Version**: 3.1.0

### Description
During the installation a dialog is displayed indicating the Exchange version is not supported, however the installer seems to complete OK.

### Steps to Reproduce

1. Ran installer
2. Left everything as default settings and clicked Install
3. Error dialog was displayed and clicked OK and installer completed

**Expected behavior:** [What you expected to happen]
No error message

**Actual behavior:** [What actually happened]
Error message

**Comment by sarthurdev** [comment]
Please try ticking "Include prerelease versions"

**Comment by MRRamsay** [comment]
Thanks @sarthurdev ! That allowed the install to complete without error. I'll let you know if I have any other issues.
