### ISSUE TITLE
How to manually update DKIM Exchange?

### ISSUE THREAD

**Issue by sashakotljarov** [Pro/dkim-exchange#278]
### Versions

- **Windows Server Version**: 2012
- **Exchange Version**: 2013CU23
- **Installed DKIM Exchange Version**: 3.0.13

### Description

Not automatically updated. Internet access is available. A proxy is not used. How do I manually update the version that I have? (no manual update instructions)

![image](https://user-images.githubusercontent.com/56763513/67146373-44ce5d00-f293-11e9-8b12-901839225fd9.png)

**Comment by sarthurdev** [comment]
You can download the source zip from the [release page](https://github.com/Pro/dkim-exchange/releases/tag/v3.2.0) and run the install.ps1 script to install manually.

**Comment by sashakotljarov** [comment]
Will I need to re-configure everything or all my settings will be saved?

**Comment by sashakotljarov** [comment]
I do not have updates, maybe because I have installed CU23, and only CU22 is supported?

**Comment by sarthurdev** [comment]
CU23 is supported, you won't need to re-configure anything though backing up the settings file and keys isn't a bad idea.

**Comment by sashakotljarov** [comment]
The update was successful. During the update, there was a request to overwrite the settings, I answered yes, but I had to answer no. The settings file was restored from the backup. Key files remained in place.
