### ISSUE TITLE
421 4.4.0 Remote server response was not RFC

### ISSUE THREAD

**Issue by joemstar** [Pro/dkim-exchange#281]
### Versions

- **Windows Server Version**: Windows Server 2016
- **Exchange Version**: Exchange 2016 RU14
- **Installed DKIM Exchange Version**: 2.3.1

### Description

When my users send email to some recipients they get a message that their message is delayed '400 4.4.7 Message delayed'and a '421 4.4.0 Remote server response was not RFC' error. I don't know for sure if this is related to DKIM but it seems to have started happening around the same time I implemented this.

**Comment by rbfajardo** [comment]
This typically means the remote server your Exchange server connected to returned a non RFC compliant response. You will want to enable protocol logging on Exchange and investigate the error. If you find an error that indicates something wrong with DKIM, please report back. Based on the error I recommend closing this issue.

**Comment by DJBenson** [comment]
Closing as per @rbfajardo.
