### ISSUE TITLE
Exchange 2019 Version 15.2.464.5

### ISSUE THREAD

**Issue by laracroft007** [Pro/dkim-exchange#282]
### Versions

- **Windows Server Version**: [2019]
- **Exchange Version**: [2019 v 15.2.464.5]
- **Installed DKIM Exchange Version**: [none yet]

### Description

I am on the newest version of Exchange, building a new server for our company.  I have been using DKIM signer on our exisitng Exchange (2010) and wanted to keep using it on the new server.  It appears I have upgraded the Exchange server to the most recent version and it is not compatible with the software.  I am completely unable to install DKIM Signer.  The exchange version is not yet supported: Version 15.2 (Build 464.5).  I see it was last updated 29 days ago.  Great Job community!

I know this is a community-based software.  Are there any plans to update it in the near future for the latest build of Exchange?

### Steps to Reproduce

1. I attempted to install version 3.2.1
2. I received the error that my version of exchange is not yet supported.

**Expected behavior:** Successful installation

**Actual behavior:** Error on my version of Exchange

**Comment by Julien-nl** [comment]
@laracroft007 i am having the same issue, hopefully we can the support soon.
big thank you for this project

**Comment by jaas666** [comment]
On the same boat with 2016 CU14

**Comment by yakir2b** [comment]
Use this workaround for meantime-
https://github.com/Pro/dkim-exchange/issues/276

Worked for me

**Comment by laracroft007** [comment]
> 
> 
> Use this workaround for meantime-
> #276
> 
> Worked for me

Thank you for the info.  I made the edits you recommended and I was able to get this installed.  Thanks a million!

**Comment by Julien-nl** [comment]
is the work around working for Exchange 2019 as well ?

**Comment by laracroft007** [comment]
Yes it is...
1.	Download the Zip file to your download folder on the Exchange server.
https://github.com/Pro/dkim-exchange
2.	Unpack the Zip file
3.	Create a folder named SRC under %userprofile% on the Exchange server
4.	Edit the install.ps1 to add the exchange server version and build at the detect version phase.  There are multiple lines that need to be edited. 
5.	Copy Src\Exchange.DkimSigner\bin\Exchange 2019 CU2 and change the folder name to "Exchange 2019 CU3"
6.	Copy all the content from the unpacked zip file ...dkim-exchange-master\Src to the SRC folder that you just created under your profile. You will also need to copy SRC to C:\Windows\System32
7.	Open Exchange Management Shell
8.	Run "Install.ps1" from the root of the unpacked Zip file
(If you get errors running the powershell script, note the errored lines and go back to edit the script.  

That installs the version 3.2.1
Remember to restart the Exchange Transportservice
From Exchange Management Shell:
Restart-Service MSExchangeTransport
Afterwards you can configure the DKIM signer

**Comment by Julien-nl** [comment]
is it possible to share the install.ps1 ? thank you

**Comment by laracroft007** [comment]
[install.txt](https://github.com/Pro/dkim-exchange/files/3912208/install.txt)

Make sure you copy Src\Exchange.DkimSigner\bin\Exchange 2019 CU2 and change the folder name to Exchange 2019 CU3 in the folder DKIM Setup\dkim-exchange-master\Src\Exchange.DkimSigner\bin

**Comment by Julien-nl** [comment]
i've done but still getting this error
`[PS] C:\Users\admin\Downloads\dkim-exchange-master\dkim-exchange-master>.\install.ps1
At C:\Users\admin\Downloads\dkim-exchange-master\dkim-exchange-master\install.ps1:164 char:9
+     throw "The exchange version is not yet supported: " + $exchserver ...
+            ~~~
Unexpected token 'The' in expression or statement.
At C:\Users\admin\Downloads\dkim-exchange-master\dkim-exchange-master\install.ps1:199 char:162
+ ... n't forget to setup all the keys! When done and saved press 'Return'"
+                                                                        ~~
The string is missing the terminator: '.
At C:\Users\admin\Downloads\dkim-exchange-master\dkim-exchange-master\install.ps1:161 char:163
+ ... ).minor -eq 2 -and ($exchserver.admindisplayversion).build -eq 464) {
+                                                                         ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken`

do you mean i have to copy and past the folder Exchange 2019 CU3 to DKIM Setup\dkim-exchange-master\Src\Exchange.DkimSigner\bin ?

**Comment by laracroft007** [comment]
Go to the bin folder and copy the Exchange 2019 CU2 and paste it to the same location, then rename it to Exchange 2019 CU3 - listed below as step 5

It should work for you.  Here are my notes, that I created above in my post just after my successful install.


1.   Download the Zip file to your download folder on the Exchange server.  dkim-exchange-master.zip
    https://github.com/Pro/dkim-exchange

2.   Unpack the Zip file

3.  Create a folder named SRC under %userprofile% on the Exchange server

4.  Edit the install.ps1 to add the exchange server version and build at the detect version phase. There are multiple lines that need to be edited. - This has been done for you in install.txt about just rename it to install.ps1

5. Copy and paste Src\Exchange.DkimSigner\bin\Exchange 2019 CU2 and change the folder name to "Exchange 2019 CU3"

6. Copy all the contents from the unpacked zip file ...dkim-exchange-master\Src to the SRC folder that you just created under your profile. You will also need to copy SRC to C:\Windows\System32

 7.  Open Exchange Management Shell

8.  Run "Install.ps1" from the root of the unpacked Zip file
    (If you get errors running the powershell script, note the errored lines and go back to edit the script.)

That installs the version 3.2.1
Remember to restart the Exchange Transportservice
From Exchange Management Shell:
Restart-Service MSExchangeTransport
Afterwards you can configure the DKIM signer
EXE Program location:
C:\Program Files\Exchange DkimSigner

**Comment by Julien-nl** [comment]
Thank you so much for your support.
i really followed up your steps but still getting this error now.
`[PS] C:\Users\admin_user\Downloads\dkim-exchange-master>.\install.ps1
At C:\Users\admin_user\Downloads\dkim-exchange-master\install.ps1:164 char:9
+     throw "The exchange version is not yet supported: " + $exchserver ...
+            ~~~
Unexpected token 'The' in expression or statement.
At C:\Users\admin_user\Downloads\dkim-exchange-master\install.ps1:199 char:162
+ ... n't forget to setup all the keys! When done and saved press 'Return'"
+                                                                        ~~
The string is missing the terminator: '.
At C:\Users\admin_user\Downloads\dkim-exchange-master\install.ps1:161 char:163
+ ... ).minor -eq 2 -and ($exchserver.admindisplayversion).build -eq 464) {
+                                                                         ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken`

**Comment by Julien-nl** [comment]
the error remains on line 164, this my line 164	$EXVER="Exchange 2019 CU3"

**Comment by DJBenson** [comment]
Exchange 2019 CU3 (15.2.464.5) is available from release 3.2.2. Please refer to the [releases](https://github.com/Pro/dkim-exchange/releases) page or alternatively if you currently have the application installed it will now pull the latest version (currently 3.2.3) from the repository.

Closing as version/CU is now in latest build. Please open a new issue if you have problems installing the latest build.
