### ISSUE TITLE
Not Reading the DNS Record

### ISSUE THREAD

**Issue by rootsid** [Pro/dkim-exchange#284]
### Versions

- **Windows Server Version**: [2016]
- **Exchange Version**: [2016]
- **Installed DKIM Exchange Version**: [3.2.0]

### Description

No record found for key1_2019._domainkey.sidcysec.co.in

while it's there. tool is giving me error.

```
C:\Users\Beast-PC>nslookup -type=txt key1_2019._domainkey.sidcysec.co.in.
Server:  raspberrypi
Address:  192.168.0.130

Non-authoritative answer:
key1_2019._domainkey.sidcysec.co.in     text =

        "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg/uTrkKsYlLFvU6LgB4ks0M+IW/vYMoZGZQzeBG/dFB5ShZWcdp9s/mxZ7mw8HzAL7/uen1l2QS97havJEl/ta4dBQAfbbKIyI5hPweVPJRd75hyJihG/QnOcp2ylW7APVTJMjzbrl3KJzVZqocINbyPZyjOu98CTsZSB1/CEF2luSmmCbzxN/Me/wap0G9vv"
        "FoF0MXc+z6mE7GOe87NSDMONQoIrsHWYXlPxhO1rv8Jjqed6x7eRw1qVRzx18onR+b5tgk3tEt2N5KlX3QMhizYrCrzfXqsEJRp1JRA2LX6NnIYE67GJlcTox3Nq7uqRaEvmKSoMODlXyNwoHtA8wIDAQAB"

```

But weird thing is it's still aligning the DKIM but during authentication of headers it's being failed.

**Comment by rbfajardo** [comment]
This happens because the DNS resolver is doing a recursive lookup. If you are blocking DNS queries outside of your network, the recursive lookup fails hence why no DNS record is found. I am guessing this code was intentional as the author probably wanted to verify using public DNS/NS.

        private void btDomainCheckDNS_Click(object sender, EventArgs e)
        {
            string sFullDomain = txtDomainSelector.Text + "._domainkey." + txtDomainName.Text;
            lblDomainDNSCheckResult.Visible = false;

            try
            {
                Resolver oResolver = new Resolver();
                **oResolver.Recursion = true;**
                oResolver.UseCache = false;

                // Get the name server for the domain to avoid DNS caching
                Response oResponse = oResolver.Query(sFullDomain, QType.NS, QClass.IN);
                if (oResponse.RecordsRR.GetLength(0) > 0)
                {
                    RR oNsRecord = oResponse.RecordsRR[0];
                    if (oNsRecord.RECORD.RR.RECORD.GetType() == typeof(RecordSOA))
                    {
                        RecordSOA oSoaRecord = (RecordSOA)oNsRecord.RECORD.RR.RECORD;
                        oResolver.DnsServer = oSoaRecord.MNAME;
                    }
                }

                // Get the TXT record for DKIM
                oResponse = oResolver.Query(sFullDomain, QType.TXT, QClass.IN);
                if (oResponse.RecordsTXT.GetLength(0) > 0)
                {
                    RecordTXT oTxtRecord = oResponse.RecordsTXT[0];
                    txtDomainDNS.Text = oTxtRecord.TXT.Count > 0 ? string.Join(string.Empty, oTxtRecord.TXT) : "No record found for " + sFullDomain;

**Comment by rootsid** [comment]
Later i went through the code and created one more edge server with external adapter.

**Comment by Pro** [comment]
> I am guessing this code was intentional as the author probably wanted to verify using public DNS/NS.

Correct! I am the author of that code. 
The main reason behind this is DNS caching.
If we would query the local DNS server, it would query the external server once, and then cache that response for some time (normally 1 hour, depending on the DNS config).
In this case, even if you update the DNS entry, the local DNS server would still return the old entry and therefore it's harder to verify.

The mentioned code is querying the public DNS server to make sure it always gets the current DNS entry.
