### ISSUE TITLE
No record found for Key11

### ISSUE THREAD

**Issue by factoryfred** [Pro/dkim-exchange#292]
### Versions

- **Windows Server Version**: [Your version]
- **Exchange Version**: [Your version]
- **Installed DKIM Exchange Version**: [Your version]

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by factoryfred** [comment]
Server 2016 standard
Exchange server 2016 cu14
Dkim 3.2.3
Installed the application successfully
Ran setup succesfully to the point that the key has been generated  and the Suggested DNS record has been created as a text record. I tested this externally to confirm the syntax was correct and both testing sites reported the DKIM record correct.
When I check my record from the application I get "No record found for key1_jan2020 etc.
So before I go any further, I have noticed on Colinwilson.co.uk that under the testing response I noticed the 'x-originating-IP' is present, is this important for DKIM to work correctly, I have modified mine to not give out the IP.

**Comment by rbfajardo** [comment]
Same behavior as #284 ?

**Comment by DJBenson** [comment]
@factoryfred can you please check #284 and confirm if you are blocking external DNS resolution as this will cause the key check to fail. @rbfajardo explains why this is the case on that issue.

**Comment by factoryfred** [comment]
Hi. As you suggested it was DNS not resolving correctly for internal reasons.
thanks for the quick answer.
