### ISSUE TITLE
Issue after removing dkim

### ISSUE THREAD

**Issue by sebcal** [Pro/dkim-exchange#295]
### Versions

- **Windows Server Version**: [2016]
- **Exchange Version**: [2016 CU14]
- **Installed DKIM Exchange Version**: [3.2.3]

### Description

Hi,
I have a problem after trying dkim-exchange tool: i removed it thinking that your antispam appliance will do the job.
Normally i deleted dkim domain configs...and uninstalled it on the control panel: everything goes well and no problem at all at this time.
Two months laters, i got an error with a customer rejecting your mail because of invalid dkim key.
After looking for the problem: i saw that the old dkim signature is still in place but without certificate...so the key isn't valid anymore....
I tryed to reinstall it, it works but i got now 2 dkim signature, one valid the other one invalid.
Is it possible to Exchange to sign the outgoing mail without transportagent installed ?
If so, can you explain where is stored the signature configuration on the Exchange Server ?
And where i could check it ?
Thanks for your reply,
Best regards,
Sébastien

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by DJBenson** [comment]
It's not possible for emails to be signed without the transport agent being installed. 

If you run the following in an Exchange Management Shell session what do you get?

`Get-TransportAgent`

If DKIM is installed correctly, you should have one 'Exchange DkimSigner' transport agent at the bottom of the list.

If you have the signing agent installed, try unintsalling it, and then re-run the above command and see if the signing agent is uninstalled. If not, you can run the following from EMS to force its removal:

```
Stop-Service MSExchangeTransport
Disable-TransportAgent -Identity "Exchange DkimSigner"
Uninstall-TransportAgent -Identity "Exchange DkimSigner" 
Start-Service MSExchangeTransport 
```

You could then remove the entire installation directory at C:\Program Files\Exchange DkimSigner to ensure all binary files are removed. If you get an error about the DLL(s) being in use, issue the following commands:

```
Stop-Service W3SVC
Remove-Item "C:\Program Files\Exchange DkimSigner" -Recurse -Force -ErrorAction SilentlyContinue 
Start-Service W3SVC
```

**Comment by sebcal** [comment]
Hi DJBenson,
Thanks for your reply.

I tryed to just disable the transport Agent, but there is still a dkim signature (the old one) 

The header of one mail sent when the TA was disabled:

Content-Type: multipart/related;
boundary="_004_b85e16c8802440f7afec510a2068e6dexxxxxxx_";
type="multipart/alternative"
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; d=xxxxx.xxx; s=dkimgrp; c=relaxed/relaxed;
h=from:to:subject:date:message-id:content-type:mime-version;

After some brainstorming...the culprit was your antispam appliance, i thought that i remove dkim setting here but i was really lazy as it was enable in 2 ways there...thanks Fortimail (and my integrator) !
Sorry for my stupid case here, everything works perfectly now...that thing drived me crazy until i found the problem...and that was not on the mail server neither it was your software :)
Best regards, i'll continue using dkim-exchange as it works seamlessly.
Sébastien

**Comment by DJBenson** [comment]
Glad it's sorted.
