### ISSUE TITLE
Not issue, more of a question

### ISSUE THREAD

**Issue by Fluffythesheep** [Pro/dkim-exchange#296]
Ver 3.2.3
Server 2016
Security Update For Exchange Server 2016 CU15 (KB4536987).

Just wondered if it is safe to do an update to the current CU15 version or do I need to uninstall the DKIM signer every time there is an update ? I noticed when i tried doing an update to another CU from CU 5 i think to CU15 it didnt like it.

**Comment by mr-flibble** [comment]
Maybe this helps? https://github.com/Pro/dkim-exchange/issues/89 
and https://github.com/Pro/dkim-exchange/commit/d4492979b6cbf6680f9b83fc8ac07f881af7cdbf

**Comment by DJBenson** [comment]
I have never removed DKIM signer between upgrades (moving through EX2016 CU's and then to EX2019 - the only time I've seen issues is where a CU is greater than the supported version in DKIM signer.

**Comment by Fluffythesheep** [comment]
I think maybe that was more the case thinking about it now, it wa due to the latest dkim not supporting the latest CU. thanks for the reply and help.

**Comment by DJBenson** [comment]
Closing as appears the above resolved the query.
