### ISSUE TITLE
Configuration Question

### ISSUE THREAD

**Issue by ScottGood** [Pro/dkim-exchange#297]
### Versions

- **Windows Server Version**: 2012
- **Exchange Version**: 2013 CU23
- **Installed DKIM Exchange Version**: 3.2.0

### Description

Is it possible to disable signing of the email body?  Something along the lines of setting the optional tag l=0 would work.  I don't know if/where to do that or if it can be accomplished in another way.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by Benjile** [comment]
Hello, 
You should ask your question on the original project:
https://github.com/Pro/dkim-exchange

**Comment by mikesteele81** [comment]
The [DKIM specification](https://tools.ietf.org/html/rfc6376)'s description of the 'c' tag in section 3.5 implies that message bodies must be included in the final signature. The description of the 'l' tag seems to allow for zero lengths, but section 8.2 warns against using the 'l' tag at all. Personally, I wouldn't trust receiving mail servers to handle 'l=0' tags consistently with each other.

**Comment by DJBenson** [comment]
No further feedback since original post. Closing.
