### ISSUE TITLE
Please Add support for Exchange 2019 CU5 (15.2.595.3)

### ISSUE THREAD

**Issue by saminsayd** [Pro/dkim-exchange#298]
### 15.2.595.3

- **Windows Server Version**: 2019
- **Exchange Version**: 15.2.529.5
- **Installed DKIM Exchange Version**: v3.2.3

### Please Add support for Exchange 2019 CU5 (15.2.595.3)

Thank you in advance!

**Comment by DJBenson** [comment]
Exchange Server 2019 CU5 and Exchange Server 2016 CU16 will be added shortly.

Thanks for the prompt.

**Comment by DJBenson** [comment]
Exchange Server 2019 CU5 and Exchange Server 2016 CU16 added to [v3.2.4 release](https://github.com/Pro/dkim-exchange/releases/tag/v3.2.4).
