### ISSUE TITLE
2 exchange server in a DIAG

### ISSUE THREAD

**Issue by PeDePera** [Pro/dkim-exchange#299]
### Versions

- **Windows Server Version**: Exchange Server 2016 CU13
- **Exchange Version**: 1779.2
- **Installed DKIM Exchange Version**: 3.2.1 (Tried to 3.2.3, but it doesn't show)

### Description
We have 2 exchange servers in a DIAG, installed on the first, no problem. Install on the second, error message: Couldn't load private key for domain example.com: The given key does not have the correct type. The keyfile must include the private and public key in PEM format. It is of type: Org.BouncyCastle.Crypto.Parameters.RsaKeyParameters
[Description of the bug or feature]

### Steps to Reproduce

1. Installed software
2. Added Domain
3. Used keys from first server
4. Removed Domain
5. Created new key (new Selector)
6. Added to DNS

**Expected behavior:** [What you expected to happen]
No error messages...
**Actual behavior:** [What actually happened]

	2020-03-26T10:20:28.000	Couldn't load private key for domain example.com: The given key does not have the correct type. The keyfile must include the private and public key in PEM format. It is of type: Org.BouncyCastle.Crypto.Parameters.RsaKeyParameters

**Comment by rbfajardo** [comment]
Did you copy over the private keys?

**Comment by DJBenson** [comment]
No further feedback since original post. Closing.
