### ISSUE TITLE
Updater does not find v3.2.4 for EXCHANGE 2016 CU16

### ISSUE THREAD

**Issue by gbusoni** [Pro/dkim-exchange#302]
### Versions

- **Windows Server Version**: 2016
 **Exchange Version**: 2016 CU14
- **Installed DKIM Exchange Version**: 3.2.3

### Description

I want to update to v3.2.4 to be able to upgarde exchange to CU16, but updater finds 3.2.3 as latest version

### Steps to Reproduce

Just open DKIM

**Expected behavior:** See v3.2.4

**Actual behavior:** See v.3.2.3

**Comment by DJBenson** [comment]
Hi @gbusoni 

Are you checking the "Include prerelease versions" checkbox?

![image](https://user-images.githubusercontent.com/1013909/80204995-ca0b4380-8621-11ea-9079-79d4aca8a56a.png)

![image](https://user-images.githubusercontent.com/1013909/80205028-db545000-8621-11ea-87fe-989009fbef1f.png)

The prerelease tag normally stays on for a couple of weeks after the build is produced to ensure there are no unforeseen bugs before people put the code into their production environments so if you want pre-releases earlier you need to check that box.

That said, v3.2.4 has been out for a while now so I'm going to remove the prerelease tag now.

**Comment by DJBenson** [comment]
Done.

![image](https://user-images.githubusercontent.com/1013909/80205258-31c18e80-8622-11ea-9bb1-b67bc1b5a0b1.png)

If this resolves your issue, please close the bug.

Many thanks.

**Comment by gbusoni** [comment]
ok thanks, good to know for next time!
