### ISSUE TITLE
Existing DNS not Verifying

### ISSUE THREAD

**Issue by lsimerly** [Pro/dkim-exchange#303]
### Versions

- **Windows Server Version**: Windows Server 2008 R2
- **Exchange Version**: Exchange Server 2010 14.03.0487.000
- **Installed DKIM Exchange Version**: 3.2.4

### Description

While setting this up I am to the part where I have added the txt record to my DNS.  I can verify that is is there on mail-tester.com.  However when I click on existing DNS check it says no record found.

### Steps to Reproduce

1. Made sure that I can ping the domain
2. Verified txt record with nslookup in cmd prompt

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by DJBenson** [comment]
Please check #292 and #284 and see if this also applies to you. Whenever we've seen such DNS issues it's been because external DNS resolution is blocked which is required for the validation check to work.

**Comment by DJBenson** [comment]
No further feedback provided. Closing.
