### ISSUE TITLE
Please Add support for Exchange 2016 CU16 (15.1.1979.3)  Thank you in advance!

### ISSUE THREAD

**Issue by ngstargate101** [Pro/dkim-exchange#304]
### Versions

- **Windows Server Version**: [2016]
- **Exchange Version**: [15.1.1713.5] 
- **Installed DKIM Exchange Version**: [3.2.4]

### Description

Please Add support for Exchange 2016 CU16

thanks in advance

**Comment by DJBenson** [comment]
This is already supported.

https://github.com/Pro/dkim-exchange/releases/tag/v3.2.4

**Comment by DJBenson** [comment]
Closing as version is already supported.
