### ISSUE TITLE
Please Add support for Exchange 2019 CU6 (15.02.0659.004) Thank you in advance!

### ISSUE THREAD

**Issue by kestrel000999** [Pro/dkim-exchange#305]
Versions:
Windows Server Version: [Windows Server 2019 Standard]
Exchange Version: [15.02.0659.004]
Installed DKIM Exchange Version: [3.2.4]
Description:
Please Add support for Exchange 2019 CU6

thanks in advance !

**Comment by DJBenson** [comment]
Exchange 2019 CU6 available in v3.2.5

https://github.com/Pro/dkim-exchange/releases/tag/v3.2.5

If updating from the UI, be sure to check the pre-release option. If you'd prefer not to upgrade to a pre-release version, please wait until the build is untagged.
