### ISSUE TITLE
DKIM Signing Agen 3.2.5 no supported Exchange 2016 cu17

### ISSUE THREAD

**Issue by u2gl** [Pro/dkim-exchange#307]
### Versions

- **Windows Server Version**: [Your version] 2012r2
- **Exchange Version**: [Your version] cu17
- **Installed DKIM Exchange Version**: [Your version]3.2.5

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by u2gl** [comment]
during installation, it writes an error that this build is not supported

**Comment by DJBenson** [comment]
3.2.5 added support for EX2016 CU17 - can you please provide a screenshot of where the error is being thrown.

**Comment by DJBenson** [comment]
Actually no need, I spotted the build had been failing and found the issue. Will re-publish 3.2.5 shortly.

**Comment by DJBenson** [comment]
https://github.com/Pro/dkim-exchange/releases/tag/3.2.5.1.

**Comment by DJBenson** [comment]
https://github.com/Pro/dkim-exchange/releases/tag/3.2.6

**Comment by u2gl** [comment]
thank you very much
