### ISSUE TITLE
Please Add support for Exchange 2019 CU7 (15.2.721.2) Thank you in advance!

### ISSUE THREAD

**Issue by saminsayd** [Pro/dkim-exchange#313]
Versions:
Windows Server Version: [Windows Server 2019 Standard]
Exchange Version: [15.2.721.2]
Installed DKIM Exchange Version: [3.2.6]
Description:
Please Add support for Exchange 2019 CU7 (15.2.721.2)

thanks in advance !

**Comment by DJBenson** [comment]
Exchange 2019 CU7 and Exchange 2016 CU18 will be added shortly. I'm just downloading the latest ISO's from Visual Studio then I will compile a build.

**Comment by saminsayd** [comment]
> 
> 
> Exchange 2019 CU7 and Exchange 2016 CU18 will be added shortly. I'm just downloading the latest ISO's from Visual Studio then I will compile a build.

Thank you very much, the kindest person!

**Comment by crypt0rr** [comment]
Is there any progress on the support of CU7 and CU18?

**Comment by DJBenson** [comment]
v3.2.7 is available now.

Please ensure you check the pre-release box - as per normal procedure new releases remain on the pre-release channel for a brief period before the pre-release tag is removed.
