### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by damien-giry** [Pro/dkim-exchange#317]
Hi,

I think there is a problem with compilation in the last prerelease.

These lines in DkimSigner.sln:
line 55        Ex2016 CU1**7**|Any CPU = Ex2016 CU18|Any CPU
line 72        Ex2019 CU**6**|Any CPU = Ex2019 CU7|Any CPU

Should be:
line 55        Ex2016 CU1**8**|Any CPU = Ex2016 CU18|Any CPU
line 72        Ex2019 CU**7**|Any CPU = Ex2019 CU7|Any CPU

Thanks for keeping dkim-exchange updated :)
Br,

**Comment by DJBenson** [comment]
Apologies for this being open so long. I don't have access to my Exchange server right now but I will try and push a fix this evening (GMT).

**Comment by DJBenson** [comment]
v3.2.8 pushed - hopefully it resolves this issue.

Please be sure to check the pre-release checkbox.

**Comment by DJBenson** [comment]
Assumed fixed - please raise any new defects against the 3.2.8 release.

**Comment by u2gl** [comment]
And there is a working dkim for exchange 2019 cu19?
