### ISSUE TITLE
Existing DNS check fails even though it is verified

### ISSUE THREAD

**Issue by MrDecepticon** [Pro/dkim-exchange#318]
### Versions

- **Windows Server Version**: 2019
- **Exchange Version**: 2019 15.2.659.4
- **Installed DKIM Exchange Version**: 3.2.6

### Description

I have my DNS setup with the appropriate txt records and have verified via mxtoolbox and dkimvalidator.com as the dkim being validated.  Using the Existing DNS Check button in Domain Settings returns the no record was found.

### Steps to Reproduce

1. Setup DKIM properly 
2. Click Check under Existing DNS
3. States no record found
4. Record is verified via MXToolbox lookup and dkimvalidator.com

**Expected behavior:** Verify record after dns propogation

**Actual behavior:** Fails verification check
![2020-10-22_13-45-08](https://user-images.githubusercontent.com/38294466/96910149-0d2d5e80-146d-11eb-89b4-7a73eb2b6eda.jpg)
![2020-10-22_13-46-00](https://user-images.githubusercontent.com/38294466/96910151-0d2d5e80-146d-11eb-8c39-2eacf6d345af.jpg)

**Comment by stryqx** [comment]
If using split DNS on your external domain, you also need to add the DKIM
TXT record to your internal DNS servers.


--
Regards,
Chris Knight

**Comment by DJBenson** [comment]
Please check the info posted by @stryqx - this issue gets raised frequently and is almost always down to split-zone DNS being in place and there being a mismatch on the internal and external DNS servers. For reference, dkim-exchange makes an external DNS lookup for verification purposes.

Please close if the above resolves the issue.

**Comment by Luckyvb** [comment]
Another problem if your server do not have access to your external NS by 53 TCP(UDP) from server. By default to do real check this utility get NS servers for zone and try check txt records on NS server and if it is can not you see such message. You must check you record from external by hand.
I make PR #322 to allow check by system DNS settings, but your must now that you are doing :)
![изображение](https://user-images.githubusercontent.com/5268904/102144249-3919fe80-3e76-11eb-8b14-e99c29e7e723.png)
![изображение](https://user-images.githubusercontent.com/5268904/102144301-4b943800-3e76-11eb-9fb3-4db5d9aad57a.png)

**Comment by DJBenson** [comment]
#322 will be included in the next release, thanks @Luckyvb .

**Comment by DJBenson** [comment]
Added in [v3.2.9](https://github.com/Pro/dkim-exchange/releases/tag/v3.2.9).
