### ISSUE TITLE
Exchange 2016 CU 18

### ISSUE THREAD

**Issue by usmanafzal159** [Pro/dkim-exchange#319]
### Versions

- **Windows Server Version**: 2016
- **Exchange Version**:EXCHANGE 2016 CU 18
- **Installed DKIM Exchange Version**: NO INSTALLED ON 2016  

following Error comes while installing latest version
![Capture](https://user-images.githubusercontent.com/31029667/98370199-9e96f600-2053-11eb-9538-73bbf61b642b.jpg)

**Comment by fa2lerror** [comment]
Same Issue

**Comment by DJBenson** [comment]
This is likely due to #317.

I will try and push a fix tonight.

**Comment by fa2lerror** [comment]
Thanks DJB!!! very quick response.

**Comment by fa2lerror** [comment]
Trying to proceed on and Configure anyways. 

![image](https://user-images.githubusercontent.com/74313765/98835463-7241f780-240e-11eb-8b68-3f03c8265fc2.png)

**Comment by fa2lerror** [comment]
3rd time worked. I had to use the check mark to include prerelease version.

![image](https://user-images.githubusercontent.com/74313765/98836031-352a3500-240f-11eb-9f28-6b1b0f37637c.png)

It appears to be working now.
![image](https://user-images.githubusercontent.com/74313765/98836393-a1a53400-240f-11eb-9bad-aea89a224838.png)

**Comment by fa2lerror** [comment]
Everything worked fine and is fully functional once I paid attention to the required Check mark to included prerelease.

**Comment by fa2lerror** [comment]
The last question... Do I need to keep the software updated with current versions as they are released? or is it really once working forget about updates?

**Comment by DJBenson** [comment]
v3.2.8 pushed - hopefully it resolves this issue.

Please be sure to check the pre-release checkbox.

**Comment by DJBenson** [comment]
@fa2lerror new versions of dkim-signer are normally released within a day or so of Microsoft releasing new Cummulative Updates and it's recommended to keep the two aligned. You may find mismatched versions work (i.e. an older version of the signer works with newer version of Exchange) but I wouldn't recommend this.

If a new CU is released without me spotting it, please raise a bug for the new version(s)  - generally Exchange 2016 and Exchange 2019 get CU's at the same time so are included in a single release of dkim-exchange.

**Comment by usmanafzal159** [comment]
> v3.2.8 pushed - hopefully it resolves this issue.
> 
> Please be sure to check the pre-release checkbox.

Please share the link for new version

**Comment by fa2lerror** [comment]
@usmanafzal159 

download the installer and next to the install button is the checkmark for include prerelease versions. make sure you use enable the prelease version option for the install.

**Comment by DJBenson** [comment]
Assumed fixed - please raise any new defects against the 3.2.8 release.
