### ISSUE TITLE
Exchange 2019 CU 7

### ISSUE THREAD

**Issue by TS-Steff** [Pro/dkim-exchange#320]
### Versions

- **Windows Server Version**: Windows 2019 Standard
- **Exchange Version**: Exchange 2019 CU 7
- **Installed DKIM Exchange Version**: Current

### Description

On installing DKIM says, Your Exchange Version is not supported

**Comment by DJBenson** [comment]
Probable duplicate of #317.

I will try and push a fix this evening (GMT).

**Comment by DJBenson** [comment]
v3.2.8 pushed - hopefully it resolves this issue.

Please be sure to check the pre-release checkbox.

**Comment by DJBenson** [comment]
Assumed fixed - please raise any new defects against the 3.2.8 release.
