### ISSUE TITLE
Update Check with 3.2.8 still detects an older version

### ISSUE THREAD

**Issue by Deckard99** [Pro/dkim-exchange#321]
After installing 3.2.8 the update detection still detects 3.2.6 (or 3.2.7) to be installed. The "about" shows the correct version of 3.2.8

**Comment by gim2000max** [comment]
3.2.7 can't update to 3.2.8 either. Exchange 2019 cu7

**Comment by gim2000max** [comment]
In about version 3.2.8

**Comment by Scifire** [comment]
Can confirm this also with a fresh install. About shows that 3.2.8 is installed but under upgrade it shows 3.2.7 installed and 3.2.8 available.

**Comment by usmanafzal159** [comment]
Same with me... showing old one

**Comment by PeteSL** [comment]
3.2.7 in loaded window, 3.2.8 in About of Configuration DKIMSigner. Tried twice to upgrade; both times completed without error.

**Comment by olliebobster** [comment]
The problem lies with the ExchangeDkimSigner.dll as the GUI's code checks the version of this DLL. The version that has been shipped with the 3.2.8 release needs it's version ID updating during compile time so that the GUI doesn't offer an upgrade to the user.

**Comment by Luckyvb** [comment]
https://github.com/Pro/dkim-exchange/releases/download/v3.2.8/Configuration.DkimSigner.zip
has library 3.2.7 if build manually and copy to server - version correct

**Comment by DJBenson** [comment]
This will be fixed in the next release due shortly which will also deliver the latest CU's for EX2016 and EX2019.
