### ISSUE TITLE
EXCH2016 CU19 support?

### ISSUE THREAD

**Issue by gbusoni** [Pro/dkim-exchange#323]
I have upgraded to Exchange 2016 CU19 but I see there is not support for it yet

**Comment by u2gl** [comment]
And there is a working dkim for exchange 2019 cu19?

**Comment by DJBenson** [comment]
I'm in the process of downloading the ISOs for the latest CU's - expect a release shortly.

**Comment by DJBenson** [comment]
Added in [v3.2.9](https://github.com/Pro/dkim-exchange/releases/tag/v3.2.9).

**Comment by u2gl** [comment]
Will there be a dkim for exchange 2016 cu20?

**Comment by DJBenson** [comment]
> Will there be a dkim for exchange 2016 cu20?

Hi - please try not to cross-post - I have responded on your post 😀
