### ISSUE TITLE
Error trying to upgrade Exchange Server 2019 CU8 to 3.2.9

### ISSUE THREAD

**Issue by bejax** [Pro/dkim-exchange#325]
### Versions

- **Windows Server Version**: Windows Server 2019
- **Exchange Version**: Exchange Server 2019 CU8 - 15.2.792.3
- **Installed DKIM Exchange Version**: 3.2.7 trying to upgrade to 3.2.9

### Description

Got an error when using the online Upgrade and trying to upgrade to 3.2.9:

```
Version not supported
Your Microsoft Exchange version isn't supported by the DKIM agent: 15.2.792.3
```

### Steps to Reproduce

1. Upgraded to Exchange Server 2019 CU8 - 15.2.792.3
2. Using Upgrade inside Configuration.DkimSigner.exe
3. Giving error _Your Microsoft Exchange version isn't supported by the DKIM agent: 15.2.792.3_

**Expected behavior:**
Successfully updated

**Actual behavior:** 
Error "Your Microsoft Exchange version isn't supported by the DKIM agent: 15.2.792.3"

Looked at https://github.com/Pro/dkim-exchange/blob/aeb4ecb5ab197b9ab80aea178f149c2565747ef7/Src/Configuration.DkimSigner/Constants.cs#L88
which may cause the problem with wrong version.
Maybe `{"15.2.792.3", "Exchange 2019 CU8"} ` is what needed.

Best Regards and Happy Christmas
Bengt

**Comment by DJBenson** [comment]
@bejax you are absolutely right, one of the downfalls of development in the early hours of the morning.

I will fix and issue a new build ASAP.

Apologies for the inconvenience.

**Comment by DJBenson** [comment]
@bejax can you try again - I've updated and rebuilt v3.2.9.

**Comment by bejax** [comment]
Will try in seconds here @DJBenson 
Many thanks for quick support!!

**Comment by bejax** [comment]
@DJBenson  Just tried but same error, I don't see a new build here at https://github.com/Pro/dkim-exchange/releases 
Could it just be a delay, github need to free up some build servers to get the job done.. :-)

**Comment by DJBenson** [comment]
I'm hoping that resolves it - I've pushed a new release (v3.3.0).

**Comment by bejax** [comment]
Installed and signer enabled, super.

Noted that it shows 3.3.1 as Installed but 3.3.0 as available. Probably a mismatch with AssemblyVersion and Release tag, bump next release to 3.3.2 will fix that.

![image](https://user-images.githubusercontent.com/59997683/103034935-5df12e80-4566-11eb-8150-35aeb166610b.png)

Now we are ready to celebrate Christmas, many thanks for help, if you in further releases with CU:s of 2019 and want me to test/check just @ me and I will be happy to help out.

Take care & Merry Christmas!
/Bengt

**Comment by DJBenson** [comment]
@bejax thanks for the offer and again sorry for the hassle - this hasn't been the best release and it's made more difficult by me not having an Exchange environment to test against right now.

If you don't mind could you just do another version check, I've just bumped the tag to 3.3.1 to keep everything aligned then I'll release the next CUs as 3.3.2.

**Comment by bejax** [comment]
It's aligned! Actually been working with git and release workflow in these days, and it convenient to be able to just delete and readd a tag. 
I close the issue! Many thanks!

![image](https://user-images.githubusercontent.com/59997683/103037283-c42c8000-456b-11eb-8d23-d09d97f27dbc.png)
