### ISSUE TITLE
Exchange 2016CU20/2019CU9

### ISSUE THREAD

**Issue by u2gl** [Pro/dkim-exchange#329]
Will there be a dkim for exchange 2016 cu20?

**Comment by DJBenson** [comment]
Hi - I will release an updated version this weekend.

**Comment by DJBenson** [comment]
I'm grabbing the ISOs now. Builds for EX2016CU20 and EX2019CU9 will be online over the weekend.

**Comment by u2gl** [comment]
I had exchange 2016 cu5 agent dkim 3.0.1. I upgraded exchange to cu 20, and dkim remained 3.0.1 well, the records work. maybe then you don't need to update dkim ?

**Comment by DJBenson** [comment]
Before I came on board as a maintainer I did used to run older versions of DKIM with newer versions of Exchange and didn't notice any problems but it's not guaranteed to work and always best to run DKIM built against the DLLs from the version of Exchange which you are running. If it's working then great, perhaps just upgrade when the new version lands (or it comes out of beta).

**Comment by u2gl** [comment]
Thank you, I'm waiting

**Comment by yetdog** [comment]
Any update on this?

**Comment by husseinsheikh** [comment]
> I'm grabbing the ISOs now. Builds for EX2016CU20 and EX2019CU9 will be online over the weekend.

Which weekend will it be available?

**Comment by cgbrooking** [comment]
Jeez guys, let's cut DJ some slack - he's not getting paid for this...

**Comment by DJBenson** [comment]
> Jeez guys, let's cut DJ some slack - he's not getting paid for this...

Came here to say exactly this. Please practice a bit of patience. I have been sick for the past two days so have other priorities. You are more than welcome to submit a pull request if you can deliver the new version faster than I can but please remember I am a volunteer and this is a free product.

I will catch up as soon as I can.

**Comment by husseinsheikh** [comment]
> Came here to say exactly this. Please practice a bit of patience. I have been sick for the past two days so have other priorities. You are more than welcome to submit a pull request if you can deliver the new version faster than I can but please remember I am a volunteer and this is a free product.
> 
> I will catch up as soon as I can.

Get well soon brother.

**Comment by Deckard99** [comment]
And for the impatient ones among us: It's was always possible to install the existing version onto newer CUs. Just take a look into the manual installation steps (and create a copy of folder CU8 for CU9) Needs about 5 Minutes to install this if really necessary.

**Comment by yetdog** [comment]
Holy smokes fellas - RELAX. It was a simple check-in based on the "over the weekend" comment. I assure you there were no pitchforks out. Appreciate all @DJBenson does!

**Comment by DJBenson** [comment]
New build added. Please ensure you check for beta versions as usual. Beta tag will be removed if no issues within the next couple of weeks.

**Comment by DJBenson** [comment]
> Holy smokes fellas - RELAX. It was a simple check-in based on the "over the weekend" comment. I assure you there were no pitchforks out. Appreciate all @DJBenson does!

Sorry if it sounded touchy, I was feeling pretty crappy, no bad feeling intended.

**Comment by bejax** [comment]
> New build added. Please ensure you check for beta versions as usual. Beta tag will be removed if no issues within the next couple of weeks.

Can confirm the build works perfect for 2019CU9.
Kudos to @DJBenson, great work, and hope you are feeling better!

**Comment by MisterSausage** [comment]
Tested 3.3.2 and also manually read through the diffs. It's an uncomplicated release and looks good to go to me.
