### ISSUE TITLE
Exchange Server 2016 CU 20 

### ISSUE THREAD

**Issue by husseinsheikh** [Pro/dkim-exchange#330]
### Versions

- **Windows Server Version**: Windows Server 2012 R2
- **Exchange Version**: 2016 CU 20
- **Installed DKIM Exchange Version**: N/A

### Description

Getting an error message that DKIM Signer is not supported with your Exchange Server CU 20

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by DJBenson** [comment]
New build added. Please ensure you check for beta versions as usual. Beta tag will be removed if no issues within the next couple of weeks.
