### ISSUE TITLE
Version for 2016 CU20

### ISSUE THREAD

**Issue by Clayman59** [Pro/dkim-exchange#332]
### Versions

- **Windows Server Version**: [2016]
- **Exchange Version**: [2016 build: 15.1.2242.4]
- **Installed DKIM Exchange Version**: [3.2.7]

### Description

[Cannot upgrade due to my version being "incompatible"]

### Steps to Reproduce

1. [Click on Upgrade button]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [that it would simply upgrade]

**Actual behavior:** [Threw an error and exited setup]

**Comment by DJBenson** [comment]
Have you enabled beta versions? The latest build (3.3.2) is in beta for the moment as is the case with all new releases.

**Comment by DJBenson** [comment]
We’ve had confirmed cases of EX2016CU20 working fine with v3.3.2.

**Comment by smccaffity** [comment]
Has there been any update on this issue?
I have the same problem when I run the installer.
"Include prerelease versions" enabled
"Install from Web" v3.3.2
Generates Error:
Version not supported
Your Microsoft Exchange version isn't supported by the DKIM agent:
15.1.2242.4

Host OS:
Server 2016 Standard 
Exchange Version:
Microsoft Exchange Server 2016 Cumulative Update 20

**Comment by DJBenson** [comment]
No further response received, assuming issue resolved. Closing.

**Comment by smccaffity** [comment]
I was able to get resolve the issue by downloading the beta version and installing it directly.
Thank you for following up. 👍

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
