### ISSUE TITLE
Exchange 2019 CU9

### ISSUE THREAD

**Issue by dreamMB** [Pro/dkim-exchange#334]
### Versions

- **Windows Server Version**: Windows Server 2019 Dtc
- **Exchange Version**: Exchange 2019 CU9 - 15.2 - 858.5
- **Installed DKIM Exchange Version**: 3.31

### Description

Actually not getting installed / configured... lack of support for CU9?

Latest DKIM version is well downloaded but after clicking Install button, the app indicates a version incompatible with CU9 and don't let me to setup DKIM.

Thanks

**Comment by akecheta159** [comment]
I fixed Issue by downloading v3.3.2 and there is a problem with name conversion to fix it you need to change cames manually yourdomain.pem and yourdomain.pub check files before changing names... it loads public key instead of private key to domain settings

**Comment by akecheta159** [comment]
This is the URL you can check your DKIM your configuration.

**Comment by LanfranchiR** [comment]
No support yet for CU9?

**Comment by cgbrooking** [comment]
Yes, in 3.3.2, which is still in beta, but working well for most people.

**Comment by DJBenson** [comment]
v3.3.2 is considered stable now. Closing.
