### ISSUE TITLE
EXCHANGE DKIM SIGNER is not signing emails sent on OWA/PHONE

### ISSUE THREAD

**Issue by j0rt3g4** [Pro/dkim-exchange#338]
### Versions

- **Windows Server Version**: Exchange server 2021 STD
- **Exchange Version**: 2016 Version 15.1 (Build 2176.2)
- **Installed DKIM Exchange Version**: [3.3.1]

### Description
DKIM sign only emails sent by Outlook desktop APP
OWA and Phones are not signed
Outlook desktop works as expected.

### Steps to Reproduce

1. Send emails to https://www.appmaildev.com/es/dkim

**Expected behavior:** [What you expected to happen]
Sign all messages
**Actual behavior:** [What actually happened]
Signing only emails sent using Outlook

**Comment by DJBenson** [comment]
Hi

I've just sent a couple of test mails to that validator and they all passed. I tried from iOS Mail, OWA (self hosted) and Outlook on macos.

There is no logical explanation why different clients would behave differently, they all go through the same agent regardless of client.

Do you have your signing agent correctly configured with the lowest priority/highest number? In the UI ensure the signing agent is the bottom of the list.

I cannot think of any other reason why this may happen but I'm happy that the agent is signing mails regardless of client as per my tests.

**Comment by j0rt3g4** [comment]
Hello @DJBenson 
I got this:
![image](https://user-images.githubusercontent.com/5489996/122652651-79985480-d105-11eb-8b11-01f8f56a4f6f.png)

![image](https://user-images.githubusercontent.com/5489996/122652673-8c128e00-d105-11eb-9083-f5d1d897c091.png)

![image](https://user-images.githubusercontent.com/5489996/122652693-a6e50280-d105-11eb-936f-fb079725826c.png)

I'd say it is, do you see any error in there?

**Comment by j0rt3g4** [comment]
Received: from dispatch1-us1.ppe-hosted.com (dispatch1-us1.ppe-hosted.com [148.163.129.48])
	by relay-7.us-west-2.relay-prod (Postfix) with ESMTPS id AACED25618
	for <XMi7yaasPNQcGJ@dkimvalidator.com>; Sat, 19 Jun 2021 18:54:28 +0000 (UTC)
X-Virus-Scanned: Proofpoint Essentials engine
Received: from xxx
	by xxx (PPE Hosted ESMTP Server) with ESMTPS id 64A71260075
	for <XMi7yaasPNQcGJ@dkimvalidator.com>; Sat, 19 Jun 2021 18:54:27 +0000 (UTC)
Received: from xxxEXCHANGE02.gpt.local (mail.greatplainstowers.com [96.3.21.74])
	by mx1-us1.ppe-hosted.com (PPE Hosted ESMTP Server) with ESMTP id 3F53B4C006C
	for <XMi7yaasPNQcGJ@dkimvalidator.com>; Sat, 19 Jun 2021 18:54:27 +0000 (UTC)
Content-Language: en-US
Content-Type: multipart/alternative;
	boundary="_000_fe205e745abd46d79ef57f0741e34e81greatplainstowerscom_"
From: Chad Ohman <Chad@xxx>
To: "XMi7yaasPNQcGJ@dkimvalidator.com" <XMi7yaasPNQcGJ@dkimvalidator.com>
Subject: 1
Date: Sat, 19 Jun 2021 18:54:23 +0000
Message-ID: <fe205e745abd46d79ef57f0741e34e81@xxx>
MIME-Version: 1.0
X-MDID: 1624128867-BC_b7O0En6sv

--_000_fe205e745abd46d79ef57f0741e34e81greatplainstowerscom_
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable



--_000_fe205e745abd46d79ef57f0741e34e81greatplainstowerscom_
Content-Type: text/html; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-=
1">
<style type=3D"text/css" style=3D"display:none;"></style>
</head>
<body dir=3D"ltr">
<div id=3D"divtagdefaultwrapper" style=3D"font-size:12pt;color:#000000;font=
-family:Calibri,Helvetica,sans-serif;" dir=3D"ltr">
<p><br>
</p>
</div>
</body>
</html>

--_000_fe205e745abd46d79ef57f0741e34e81greatplainstowerscom_--



---


DKIM Information:

DKIM Signature

This message does not contain a DKIM Signature

**Comment by DJBenson** [comment]
@j0rt3g4 the signing agent should be at the bottom of the list, priority 10 in your case. I can't say for sure if this will fix your issue but as per the hint in the UI, the signing agent should have the lowest priority (highest number);

![image](https://user-images.githubusercontent.com/1013909/122652788-8da97980-d138-11eb-8dfc-1e116bfd4156.png)

**Comment by DJBenson** [comment]
![image](https://user-images.githubusercontent.com/1013909/122652932-6f904900-d139-11eb-88dd-36a8b8b9b7f3.png)

**Comment by j0rt3g4** [comment]
@DJBenson 
Alright Corrected.
![image](https://user-images.githubusercontent.com/5489996/122652922-1ad3da80-d107-11eb-95f7-18e5f486b7d7.png)

[report-46077ac9.txt](https://github.com/Pro/dkim-exchange/files/6681234/report-46077ac9.txt)

**Comment by j0rt3g4** [comment]
@DJBenson  I think I've figure it out where  the issue was,
The issue was that I was sending Email using OWA "on" the server instead of any external, so for whatever reason is not signing those messages if I'm "ON" the server.
Did you know that ?

**Comment by DJBenson** [comment]
Mmm OK  - it's hard to visualise this without knowing how your Exchange infrastructure is set up.

I'm what you might call "an enthusiast" so my server was set up to help me learn Exchange but I only have a single VM install with the roles on the single instance.

**Comment by j0rt3g4** [comment]
I see @DJBenson 
It's a simple setup, Exchange server 2016 on a VM (like the one you had) that's why It's nothing too fancy :)
