### ISSUE TITLE
Please Add support for Exchange 2019 CU10 (15.2.922.7) Thank you in advance!

### ISSUE THREAD

**Issue by saminsayd** [Pro/dkim-exchange#339]
Versions:
Windows Server Version: [Windows Server 2019 Standard]
Exchange Version: [15.2.858.12]
Installed DKIM Exchange Version: [3.3.2]
Description:
Please Add support for Exchange 2019 CU10 (15.2.922.7)

thanks in advance !

**Comment by AndrewV8S** [comment]
yes, please! that would be great! The June 2021 Quarterly Exchange Update was release on 06-29-2021. Just can't wait to install it! :)

**Comment by cgbrooking** [comment]
I have prepped the changes for this - I can create a fork, but I'm also happy to be added as a contributor.

**Comment by CFM-Tech** [comment]
Also looking for Exchange 2019 CU10 (15.2 922.7)

**Comment by MisterSausage** [comment]
Added support for 2019 CU10 and 2016 CU21 and created a pull request. #340

**Comment by DJBenson** [comment]
Merged #340 thanks @MisterSausage .

New binary release now available: https://github.com/Pro/dkim-exchange/releases/tag/v3.3.3

If upgrading via the UI, ensure to theck the pre-release/beta checkbox.

**Comment by MisterSausage** [comment]
@DJBenson More than happy to do this again next time if it's useful.
