### ISSUE TITLE
Need support for Exchange Server 2016 CU21

### ISSUE THREAD

**Issue by akpeelo** [Pro/dkim-exchange#343]
I will be grateful if support for Exchange server 2016 CU21 is made available.

**Comment by cgbrooking** [comment]
v3.3.3 DOES support CU21.

**Comment by akpeelo** [comment]
in the source code zip folder, there is no v3.3.3. there is only v3.3.2 and
when installing i get an error that the transport is not compatible with
installed exchange version.

When i check the include prerelease versions box, it installs alright but
then on the domain settings tab, the check Existing DNS always returns "No
record found for domain"

**Comment by akpeelo** [comment]
even though i've configured the application on my server as contained in this tutorial https://mangolassi.it/topic/21623/setup-dkim-with-exchange-2013-2016-inhouse-server, i still get "No record found" when i click on check for existing DNS. Please kindly help

**Comment by DJBenson** [comment]
What happens if you check the “External NS” checkbox when you perform the test?

**Comment by akpeelo** [comment]
Well on my interface i.e v3.3.3, there is no "External NS" instead there is
"Direct NS" checkbox. if i check that box, the feedback "No record found
for xxxxxx._domainkey.domain.com" where xxxxxxis the selector and domain.com
is the domain.

**Comment by akpeelo** [comment]
please any assistance will be highly appreciated.

**Comment by akpeelo** [comment]
if i do nslookup on the dns record i get a response which presupposes that the problem is from the application on my server. kindly help.

**Comment by cgbrooking** [comment]
Do you have your DKIM records configured on your local DNS as well as your external DNS?  And have you checked to see if your messages are getting signed?  There are plenty of online tools to check this, eg https://www.appmaildev.com/en/dkim

**Comment by akpeelo** [comment]
so i created DKIM records on my local DNS (microsoft domain Controller DNS) just as i had done with the external dns. then clicked on the check button. Now it says DNS Public key is correct. when i checked with my gmail account, there is the signed fiel there with my domain.
Thanks all for your help. I wonder why most online guides dont emphasis on the creation of local dns? Anyway thanks for your help.

**Comment by cgbrooking** [comment]
You don't need local DNS, because it's only external clients that will be checking your signature.  I've never understood how the DNS check is useful, since I can't see how it would ever check external DNS, and it's external DNS that's important.
