### ISSUE TITLE
Cannot download the file "Configuration.DkimSigner.zip" v3.3.4. Show error "Error 503 Backend.max_conn reached".

### ISSUE THREAD

**Issue by abdullah467** [Pro/dkim-exchange#352]
### Versions

- **Windows Server Version**: [Your version]
- **Exchange Version**: [Your version]
- **Installed DKIM Exchange Version**: [Your version]

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by abdullah467** [comment]
Versions
Windows Server Version: 2016
Exchange Version: 2016 CU 22

Description
Error 503 Backend.max_conn reached
Backend.max_conn reached

Guru Mediation:
Details: cache-hyd1100035-HYD 1636628504 774226685

**Comment by DJBenson** [comment]
Please try latest version.
