### ISSUE TITLE
Exchange 2016 CU20 - Settings Error - Couldn't load the settings file

### ISSUE THREAD

**Issue by jlc2426** [Pro/dkim-exchange#354]
### Versions

- **Windows Server Version**: 2012 R2 Standard - Version 6.3 (Build 9600)
- **Exchange Version**: 15.1.2242.4 
- **Installed DKIM Exchange Version**: 3.3.4.

### Description

I am having trouble getting the DKIM Signer to install on my Exchange server. I can download and install the GUI package and get through the DKIM Signer installation. When completed and running the application from the Program folder, I get the Settings Error and the GUI opens indicating that the Signer is not installed. I go through the installation process again and same result. 

### Steps to Reproduce

1. Download the latest GUI package, extract and start Configuration.DkimSigner.exe
2. Install latest version from GUI. Process occurs with no errors. Close installer. 
3. Launch configuration.dkim.signer from Programs folder. Opens up and shows Transport Service Status running.

**Expected behavior:** DKIM Signer installed and ready to configure.

**Actual behavior:** Settings Error - Couldn't load the settings file. Setting it to default values. GUI indicates that DKIM Signer not installed and the Configure button is greyed out. 

Any idea why this may be occurring? The Exchange Server is running on a VM. 

Thank you.

**Comment by cdclement** [comment]
Also experiencing this problem:

**Windows Server Version:** 2019 Standard
**Exchange Version:** 15.2 (15.02.0986.014)
**Installed DKIM Exchange Version:** 3.3.4
