### ISSUE TITLE
Request new release for Exchange Server 2019 CU12

### ISSUE THREAD

**Issue by BerndFranzen** [Pro/dkim-exchange#357]
### Versions

- **Windows Server Version**: Windows Server 2022
- **Exchange Version**: Exchange Server 2019 CU12
- **Installed DKIM Exchange Version**: Not installed, v 3.3.4 not working

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by DJBenson** [comment]
v3.4.0 is now generally available.
