### ISSUE TITLE
Any ETA on support for 2016 CU23?

### ISSUE THREAD

**Issue by TreborSinad** [Pro/dkim-exchange#363]
Hello,

Any ETA on support for 2016 CU23?

Thanks again,
Robert

**Comment by rodiebar** [comment]
Hello, i have installed now 3.4 version and it works fine. i have a message from installer that says the version is not compatible, but i can proced with the installation.

Thanks!!!!

**Comment by TreborSinad** [comment]
Huh, that seems to work. neat trick. Thanks! 
One more quick question, Should the name.domainkey.domain.com DNS entry be both in the Internal as well as the External facing DNS servers?

**Comment by DJBenson** [comment]
It depends on whether you use internal or external validation.

**Comment by TreborSinad** [comment]
I see, to validate the domain in DkimSigner, it requires the DNS entry in the internal DNS, but to validate DKIM for external e-mail, the External DNS also requires the entry. So i guess both are needed.

**Comment by gilm0079** [comment]
Good hearing the 3.4.0 pre-release is working. @DJBenson @MisterSausage is there an estimate when 3.4.0 will go into release? Trying to gauge whether we also move forward with pre-release or just wait for the release. Thanks for the great work!

**Comment by DJBenson** [comment]
Unless we start hearing of issues (which we haven't yet) then I can flip the switch on the prerelease flag and make it GA.

**Comment by DJBenson** [comment]
I've removed the pre-release tag from 3.4.0.

**Comment by boredinballard** [comment]
Hi all,

I have the same issue with 3.4.0 (or any other version) on Exchange 2016 CU23 and Server 2016, the management screen will not load, no matter how many attempts at re-opening. Reboots do not resolve.

**Comment by boredinballard** [comment]
Figured it out when digging into the eventlog:

Install-TransportAgent 
-Confirm "False" -Name "Exchange DkimSigner" -TransportAgentFactory "Exchange.DkimSigner.DkimSigningRoutingAgentFactory" -AssemblyPath "C:\Program Files\Exchange DkimSigner\ExchangeDkimSigner.dll" 
System.ArgumentException: The Transport Agent assembly file "C:\Program Files\Exchange DkimSigner\ExchangeDkimSigner.dll" doesn't exist. Parameter name: AssemblyPath at Microsoft.Exchange.Configuration.Tasks.Task.ThrowError(Exception exception, ErrorCategory errorCategory, Object target, String helpUrl) at Microsoft.Exchange.Management.AgentTasks.InstallTransportAgent.InternalValidate() at Microsoft.Exchange.Configuration.Tasks.Task.<ProcessRecord>b__91_1() at Microsoft.Exchange.Configuration.Tasks.Task.InvokeRetryableFunc(String funcName, Action func, Boolean terminatePipelineIfFailed) 


For whatever reason, the dkimsigner.dll doesn't get installed into program files. But if I run the configurator and have it install again, it gets the dll, and now the configurator opens.
