### ISSUE TITLE
Create Wiki entries for documentation

### ISSUE THREAD

**Issue by Pro** [Pro/dkim-exchange#49]
We should create wiki entries for:
- How to install using GUI or with install.ps1 script
- How to configure the agent with the GUI or manually editing settings.xml
- https://github.com/Pro/dkim-exchange/blob/master/TROUBLESHOOT.md to wiki page
- Notes for developers (how to build the .dll, libraries needed, how to release)

**Comment by kungfutennis** [comment]
Maybe a dumb question, but which server role is this supposed to be installed on?  CAS or HUB?  Or Edge Transport if you have Edge?  or HUB if you don't?  The pay versions of this kind of thing imply it's for Edge Transport, because if you didn't have Edge Transport, you'd hopefully have a smarthost that could do the DKIM signing natively.

**Comment by AlexLaroche** [comment]
It suppose to be installed on Edge and Hub server role depending of your infrastructure (Edge Transport or Mailbox server role on Exchange 2013).

**Comment by kungfutennis** [comment]
Alexandre,

Thank you for taking the time to answer my question so quickly.

Thank you also for all the hard work.

Yung Kim

**Comment by mr-flibble** [comment]
Sorry for the silly question, but I did not find the answer anywhere.

**What is the recommended way to upgrade to a newer Exchange CU?**
Should I DKIM Signer before deactivate or uninstall, or update it? Or none of it and update it after upgrade to the new CU? Thank you.

**Comment by pavelkos** [comment]
Hello! Cannot install (Exchange 2013 on WS 2008 R2)

![2015-07-07_15-48-10](https://cloud.githubusercontent.com/assets/13079391/8546354/d1d95160-24bf-11e5-8f8c-236c886dc559.jpg)

**Comment by DJBenson** [comment]
Documentation migrated to wiki.
