### ISSUE TITLE
 Access to the Key Path is denied.

### ISSUE THREAD

**Issue by mirsaeedii** [Pro/dkim-exchange#78]
Thanks you guys for your great work! Unfortunately DKIMSigner, does not sign messages in our server. In The EventLog Viewer, Following error is shown:

Couldn't load the key 'C:\Program Files\Exchange DkimSigner\keys\sohato.com.xml' for domain sohato.com. Error message: Access to the path 'C:\Program Files\Exchange DkimSigner\keys\sohato.com.xml' is denied.

what should I do?

**Comment by mirsaeedii** [comment]
I Change the Key Location to be on my desktop. Now I`m getting another error:

The private key for domain sohato.com wasn't found: C:\Users\admin\Desktop\keys\sohato.com.xml

**Comment by Pro** [comment]
Can you check the access rights for the folder `C:\Program Files\Exchange DkimSigner\keys\` and make sure that the files exist.
I think the user `SYSTEM` needs access rights.

Regarding the files on your desktop: Are you sure that the path is correct?
Please try another path, e.g. `C:\keys\foo.xml`

**Comment by mirsaeedii** [comment]
I Solved it. It was about security and permission issues. I gave Full Access to the"keys" folder to the special "Everyone" user (of our Active Directory Domain). Now everything is working smoothly. thanks :)

**Comment by Waqas-javid** [comment]
Add "Network Service" and assign permissions to it.

![image](https://github.com/Pro/dkim-exchange/assets/170987931/eaa7ec19-4b49-41d2-8584-e676a29b391c)
