### ISSUE TITLE
.NET requirements

### ISSUE THREAD

**Issue by hutch85** [Pro/dkim-exchange#80]
This is just more of an FYI; I went to install the latest version on Exchange 2010 SP3 and the installer says it needs .NET v4.5 installed.  Not a big deal but the Supported Versions section says .NET 3.5 for 2010 :-)

Thanks,
Mike

**Comment by AlexLaroche** [comment]
The .dll (Exchange DKIM Signer) is compiled for .NET 3.5 (Exchange 2007 and 2010) or .NET 4 (Exchange 2013)

The .exe (Configuration DKIM Signer) is compiled for .NET 4.5.

It's possible to don't install .NET 4.5 but you will have to manually install (powershell script:  install.ps1) and configure the Exchange DKIM Signer (Edit with an editor .dll.config).

**Comment by hutch85** [comment]
Thanks Alex!
