### ISSUE TITLE
Exchange 2013 CU8 (15.0.1076.9)

### ISSUE THREAD

**Issue by topcats** [Pro/dkim-exchange#81]
Hi there

Any news when support for CU8 is going to be released?

Thanks

TC

**Comment by Pro** [comment]
Do you have it already installed and could you send us the required files (zip them, change the file extension to .png and upload them here)

C:\Program Files\Microsoft\Exchange Server\V14\Public
Microsoft.Exchange.Data.Common.dll
Microsoft.Exchange.Data.Common.xml
Microsoft.Exchange.Data.Transport.dll
Microsoft.Exchange.Data.Transport.xml

We can then recompile it for this version.

**Comment by topcats** [comment]
Hi



 Yes already installed



Files attached

However from a V15\Public folder



Thanks



T







________________________________

**Comment by Pro** [comment]
Didn't get the attachments. Github doesn't allow to respond to email including an attachment. You need to upload them directly on the Github page or send me a link where I can download the files (e.g. Dropbox or any other file hoster)

**Comment by topcats** [comment]
hmm it would also appear that I can't attach a zip file to this post either...

http://dev.the-owls.org/dkim-exchange/Exchange2013-CU8.zip

**Comment by AlexLaroche** [comment]
@Pro : Can you create a new release v2.1.4?

**Comment by Pro** [comment]
https://github.com/Pro/dkim-exchange/releases/tag/v2.1.4
