### ISSUE TITLE
Does simple/simple (normalizing) break S/MIME?

### ISSUE THREAD

**Issue by Pro** [Pro/dkim-exchange#87]
If canonicalization `simple` is used, it may break an already existing S/MIME signature because the body is changed (i.e. line endings and header names are normalized according to the DKIM RFC)

This needs further investigation. See also #86

**Comment by AlexLaroche** [comment]
@Pro : If canonicalization simple is active, we calculate the dkim signature on the original email. If canonicalization relaxed is active, we normalize a copy  of the email to calculate the email. We aren't supposed to change the original email. The only thing the signer is suppose to do is to add the calculated DKIM signature.

**Comment by Pro** [comment]
Oh right, I mixed simple and relaxed up.
But I wasn't sure if if S/MIME also includes headers into the signature. Looked that up now and also the tests from Bug #86 confirm that we should be fine.
