### ISSUE TITLE
Exchange 2013 CU9

### ISSUE THREAD

**Issue by rbfajardo** [Pro/dkim-exchange#88]
Will there be official support for Exchange 2013 CU9? Is the current build for CU8 compatible with CU9?

**Comment by pavelkos** [comment]
Current build is incompatible with CU9

**Comment by Pro** [comment]
CU8 isn't compatible with CU9 but we will release a version for CU9.
Can you upload the required DDLs somewhere and paste the link here?
See: https://github.com/Pro/dkim-exchange#required-dlls-for-developing

**Comment by pavelkos** [comment]
Please check requested files - https://dl.dropboxusercontent.com/u/11127662/Exch.2013.CU9.Public.zip

**Comment by Pro** [comment]
https://github.com/Pro/dkim-exchange/releases/tag/v2.1.5-beta

**Comment by pavelkos** [comment]
![2015-07-05_15-21-17](https://cloud.githubusercontent.com/assets/13079391/8511619/957067b4-2329-11e5-9f4d-8ee8b4886c2e.jpg)

Cannot install or upgrade

**Comment by pavelkos** [comment]
![2015-07-05_15-28-06](https://cloud.githubusercontent.com/assets/13079391/8511637/937efea6-232a-11e5-9d28-f448ff8af711.jpg)

![2015-07-05_15-21-17](https://cloud.githubusercontent.com/assets/13079391/8511638/97cc4496-232a-11e5-91c6-a12fe7256855.jpg)

Installer don't work

**Comment by Pro** [comment]
Will check that, thanks!

**Comment by AlexLaroche** [comment]
The problem is locate here : Configuration.DkimSigner/InstallWindow.cs, line 159 à 181

```
// ###########################################
// ### IS Exchange version supported?      ###
// ###########################################

string agentExchangeVersionPath = "";

foreach (KeyValuePair<string, string> entry in Constants.DKIM_SIGNER_VERSION_DIRECTORY)
{
    if (exchangeVersion.StartsWith(entry.Key))
    {
        agentExchangeVersionPath = entry.Value;
        break;
    }
}

if (agentExchangeVersionPath == "")
{
    MessageBox.Show(this, "Your Microsoft Exchange version isn't supported by the DKIM agent: " + exchangeVersion, "Version not supported", MessageBoxButtons.OK, MessageBoxIcon.Error);
}
else
{
    this.lbDownloadFiles.Enabled = true;
}
```

**Comment by Pro** [comment]
Yep, thanks, forgot to add the CU9 Version string. I will fix that

**Comment by Pro** [comment]
https://github.com/Pro/dkim-exchange/releases/tag/v2.1.5-beta.2

**Comment by pavelkos** [comment]
Clean install work correctly. Upgrade from 2.1.4 work if I'm delete / rename folder with 2.1.4 version in program files folder

**Comment by Pro** [comment]
That's strange, I just tested to update from v2.1.4 to 2.1.5-beta.2 and it worked for me. Will investigate that further. Thanks for the feedback.

**Comment by pavelkos** [comment]
anyway thank you for greates product! ;)
