### ISSUE TITLE
Add to readme: Upgrade approach for new CU

### ISSUE THREAD

**Issue by mr-flibble** [Pro/dkim-exchange#89]
Sorry for the silly question, but I did not find the answer anywhere.

What is the recommended way to upgrade to a newer Exchange CU if I have DKIM already installed?
Should I DKIM Signer before deactivate or uninstall, or update it? Or none of it and update it after upgrade to the new CU?
I think it would be good to add this information to the readme. Thank you.

**Comment by gogglespisano** [comment]
I've wondered the same thing.  Since DKIM will break during the upgrade, should it be turned off before the update, then upgraded after exchange?  Is there any harm in leaving it running during the exchange upgrade?

The biggest concern would be causing the exchange update to fail or exchange transport fail to start after update.

**Comment by rbfajardo** [comment]
If the concern is the transport service would fail to start, you can disable the DKIM transport agent prior to a CU upgrade. (Disable-TransportAgent)

You can then upgrade the DKIM transport agent using the config executable.

**Comment by gogglespisano** [comment]
Is disabling dkim enough to keep it from literally being loaded, or just not in use?

If the dkim signer has dependencies that become incompatible during the exchange upgrade, can it cause the transport to fail to start even with the dkim signer disabled?

**Comment by Pro** [comment]
You can use the Configuration Programm shipped with the signer to disable it, the update exchange, next update DKIM, then enable it again.

Disabling DKIM will disable it entirely, thus not loading the DLL.
I'll update the Readme for the instructions

**Comment by Pro** [comment]
https://github.com/Pro/dkim-exchange/commit/d4492979b6cbf6680f9b83fc8ac07f881af7cdbf
