### ISSUE TITLE
Server 2008 R2 + Exchange 2013 CU9 Install

### ISSUE THREAD

**Issue by pavelkos** [Pro/dkim-exchange#90]
![2015-07-09_17-51-09](https://cloud.githubusercontent.com/assets/13079391/8598873/f3426c36-2665-11e5-9f37-807392522eb4.jpg)

Installer don't work on subject system

**Comment by Pro** [comment]
This looks to me that there's still a problem with detecting the correct exchange version.
I have to update my installation first to debug this. In the meantime you can download the .dll and overwrite the existing one:
https://github.com/Pro/dkim-exchange/tree/master/Src/Exchange.DkimSigner/bin/Exchange%202013%20SP1%20CU9

**Comment by AlexLaroche** [comment]
Please reopen if still not resolve.

**Comment by pavelkos** [comment]
please provide direct link for zip archive for this files, so i'm can retest
