### ISSUE TITLE
RSA Crypto files being generated in CryptoAPI directory during message signing

### ISSUE THREAD

**Issue by zrbite2k** [Pro/dkim-exchange#91]
Took a while for me to notice this, but ever since I upgraded to 2.1.3 from an old 1.8.x version, I am seeing  a small 1.45kb file created in C:\Windows\ServiceProfiles\NetworkService\AppData\Roaming\Microsoft\Crypto\RSA\S-1-5-20 for each message that is being signed. I have 5 million+ of these small ~2k files now which appear to be causing issues during disk scans and slowdowns each time new files are written here. 

Is anyone else seeing this behavior? For now I have a script cleaning up these files but am wondering if this can be prevented.

**Comment by Pro** [comment]
Thanks for your report!

This may be related to the [PersistKeyInCsp](https://msdn.microsoft.com/en-us/library/system.security.cryptography.rsacryptoserviceprovider.persistkeyincsp%28v=vs.110%29.aspx) setting.
We will investigate that further.

Which versions are you using? (Windows, Exchange, Signer)

**Comment by gogglespisano** [comment]
I had 600k+ of these from the last 15 months.

Server 2008 R2, Exchange 2010 (14.3.123.4), DKIM 2.12

**Comment by gogglespisano** [comment]
It seems to be writing 8 of these files for every email sent.  Maybe coincidentally, I have 8 domains set up in my DKIM signer.

**Comment by zrbite2k** [comment]
my environment is Windows Server 2008 R2, Exchange 2010 (14.3.123.4) SP1 RU1, DKIM 2.1.3

I do know this was not previously a problem. The oldest file dat in the Crypto\RSA\S-1-5-20 directory coincides with the date we updated to DKIM 2.1.3

**Comment by gogglespisano** [comment]
Is there any update on the cause of the RSA files?  I'm getting 10k+ of these files a week.

**Comment by Pro** [comment]
Sorry, unfortunately I didn't have much time lately to look into the problem. Hopefully I'll get some free time the coming days. If anyone of you has C# knowledge, we appreciate any help on identifying the bug :)

**Comment by gogglespisano** [comment]
I don't know if it's the best or proper fix, but this seems to work:

If you add the KeyContainerName when creating the crypto provider it will reuse the same file.  I tried adding PersistKeyInCsp = false after creating the provider but it still writes the file.  I plumbed the domain name to use as the keyName.

CspParameters cspParameters = new CspParameters { KeyContainerName = keyName };
provider = new RSACryptoServiceProvider( cspParameters );

I can make a pull request if you want to look at it and test it further?

**Comment by Pro** [comment]
I modified the RSACryptoServiceProvider creation in my previous commit:
https://github.com/Pro/dkim-exchange/commit/d77ed86409320d81ea07d84b4328e63f1f2cc61a

This now uses the `KeyContainerName`.
I couldn't test the new code yet sind my VM is still updating which may take some time. In the meantime, if you want to test it, just overwrite your current .dll with this one: https://github.com/Pro/dkim-exchange/tree/master/Src/Exchange.DkimSigner/bin

**Comment by gogglespisano** [comment]
I built your changes and it looks like it's working.  I only have one set of files generated. :)
