### ISSUE TITLE
Possible bug in btDisable.Text = (IsDkimAgentTransportInstalled ? "Disable" : "Enable")

### ISSUE THREAD

**Issue by gogglespisano** [Pro/dkim-exchange#92]
In:
        private void ExchangeTransportServiceWindows_Load(object sender, EventArgs e)
        {
            this.RefreshTransportServiceAgents();

            bool IsDkimAgentTransportInstalled = ExchangeServer.IsDkimAgentTransportInstalled();
            bool IsDkimAgentTransportEnabled = IsDkimAgentTransportInstalled && ExchangeServer.IsDkimAgentTransportEnabled();
            this.btDisable.Text = (IsDkimAgentTransportInstalled ? "Disable" : "Enable");
        }

Should it use Is...Enabled rather than Is...Installed?
            this.btDisable.Text = (IsDkimAgentTransportInstalled ? "Disable" : "Enable");

It thinks it is enable when it's disabled and then you can't enable it from the UI.

**Comment by AlexLaroche** [comment]
8c0ed68aba7593408f4596613338a8ba0a662145

**Comment by gogglespisano** [comment]
This is now backwards.  When it is enabled it should show "disable" as the choice and vice-versa.

**Comment by gogglespisano** [comment]
Also, this code should be in RefreshTransportServiceAgents so that it updates when refreshed.
