### ISSUE TITLE
Server 2008 R2 + Exchange 2013 CU9

### ISSUE THREAD

**Issue by pavelkos** [Pro/dkim-exchange#94]
![2015-08-03_21-07-53](https://cloud.githubusercontent.com/assets/13079391/9044253/228e06ae-3a24-11e5-8ecf-68358b085cd0.png)

Won't install

**Comment by Pro** [comment]
Are you using the beta release 2.1.5 or 2.1.4?
https://github.com/Pro/dkim-exchange/releases

**Comment by pavelkos** [comment]
2.1.5.beta-2

**Comment by Pro** [comment]
I just tested upgrading from version 2.0.0 to 2.1.5.beta-2 on my Windows 2012 R2 Server with Exchange 2013 CU9. It worked flawlessly. This seems to be a problem with Windows 2008.
I have to set up a new VM for testing, may take some time.

**Comment by pavelkos** [comment]
For me 2.1.5 work good on many 2012R2 + Exch 2013 CU9. Problem only with 2008 R2. If you need some files from this install - please feel free ask me about it.

**Comment by Pro** [comment]
It's quite strange that the message box above says Exchange Version `15.0.1104.5` which is definitely supported:

The check is here:
https://github.com/Pro/dkim-exchange/blob/a268bf9802a6c829d01113c94e397005d9ec839e/Src/Configuration.DkimSigner/InstallWindow.cs#L165

And the constants are defined here:
https://github.com/Pro/dkim-exchange/blob/master/Src/Configuration.DkimSigner/Constants.cs#L37

So the check at line https://github.com/Pro/dkim-exchange/blob/a268bf9802a6c829d01113c94e397005d9ec839e/Src/Configuration.DkimSigner/InstallWindow.cs#L167 should not fail for this entry. Very strange...
Needs further debugging.

**Comment by gogglespisano** [comment]
@pavelkos If you open the exchange management (power)shell window, what does this command output?

Get-ExchangeServer | fl AdminDisplayVersion

**Comment by gogglespisano** [comment]
@pavelkos Can you make sure that the Configuration.DkimSigner.exe that's running when you see the install failure message is the latest version, and not an earlier build or previous install?  Task Manager can show you where it was loaded from in the Command Line column (you may need to add this column), then check the version and timestamp on the file.

**Comment by pavelkos** [comment]
VERBOSE: Connected to exch2-wbbr2.target.local.
[PS] C:\Windows\system32>Get-ExchangeServer | fl AdminDisplayVersion
AdminDisplayVersion : Version 15.0 (Build 1104.5)

![2015-08-04_0-29-15](https://cloud.githubusercontent.com/assets/13079391/9048205/fe69ed30-3a3f-11e5-8ff6-47ee8e590990.png)

have not any previous versions installed

**Comment by gogglespisano** [comment]
Thanks @pavelkos.

When you click on install and while you have the failed install message showing, could you use Task Manager to get the full command line including parameters for Configuration.DkimSigner.exe while it's running?

**Comment by pavelkos** [comment]
Command line column is empty, no parameters

![2015-08-04_0-40-47](https://cloud.githubusercontent.com/assets/13079391/9048399/80cfccbc-3a41-11e5-99ab-0b327315fe96.png)

**Comment by gogglespisano** [comment]
Can you try running Configuration.DkimSigner.exe with only "--install" as the command line parameter.  It should open the Install window and you should be able to select the install location.  Wait several seconds before selecting the install choice and starting the install.  Does this procedure still produce the failure message?

**Comment by pavelkos** [comment]
![2015-08-04_0-58-49](https://cloud.githubusercontent.com/assets/13079391/9048730/10dbc1ce-3a44-11e5-9858-6798359579cf.png)

**Comment by gogglespisano** [comment]
I'm running out of ideas.  You shouldn't get that message unless the Configuration.DkimSigner.exe doesn't contain that version in it.  Either that or the version number looks the same, but for some reason is actually different in Unicode.  You could open the .exe in Notepad and then search for "1 1 0 4".  it should appear in a block like "1 5 . 0 . 1 1 0 4 . 5  +E x c h a n g e   2 0 1 3   S P 1   C U 9"

**Comment by gogglespisano** [comment]
FYI, the versions shown that are available to install are downloaded by the app, so an older version of the installer will show even the latest version of the software and the latest revisions, even if it isn't up to date itself with the exchange version check.

Maybe the supported version list should be downloaded with the available versions data.

**Comment by Pro** [comment]
Can you try the .exe from this zip: https://dl.dropboxusercontent.com/u/3233048/Release.zip
Open it with the command line parameter `--debug`
This will show an additional `Debug Helper` tab.

Wait until the main tab has loaded the Exchange version. Then switch to the Debug Tab and press the button. Post the message box output here (Screenshot, or just press Ctrl+C when the message box is open)

**Comment by pavelkos** [comment]
Thank you. I'm try to clean up %temp% (in temp many {guid}.zip file's with dkimsigner inside. now all work fine (2.1.5-beta2)
