### ISSUE TITLE
Support for Exchange 2016

### ISSUE THREAD

**Issue by netsujit** [Pro/dkim-exchange#96]
I know Exchange 2016 has not released yet, however it's preview release is available. We are using it on a Test environment.

We would appreciate if you add support for Exchange 2016 in one of your next beta release.

**Comment by Pro** [comment]
Can you upload the following files somewhere and post it here, so I can add Exchange 2016:

(Use the correct version instead of `V14`)

```
C:\Program Files\Microsoft\Exchange Server\V14\Public
Microsoft.Exchange.Data.Common.dll
Microsoft.Exchange.Data.Common.xml
Microsoft.Exchange.Data.Transport.dll
Microsoft.Exchange.Data.Transport.xml
```

**Comment by netsujit** [comment]
Hi there,

I've uploaded the required files here:
https://mega.nz/#!6hQhHRKA!Snj485tjalP_VgsAIcMZLt50ZFGBKCtMmXk_lrwL4K8

As per Microsoft site, the current version number for Exchange 2016 is 15.01.0225.016

Let me know if anything else is required.

**Comment by Pro** [comment]
https://github.com/Pro/dkim-exchange/commit/0973c59f53c2f0cda25d210910eaaf6afb9d2aa9
