### ISSUE TITLE
2013 CU9 async error

### ISSUE THREAD

**Issue by kimurin** [Pro/dkim-exchange#97]
Hi.
I'am constantly getting error in Event Viewer after upgrading to 2013 CU9 and 2.1.5:
**"Agent 'Exchange DkimSigner' went async but did not call Resume on the new thread, while handling event 'OnCategorizedMessage'".**
Although this had no impact on functionality.

**Comment by Pro** [comment]
Seems to be an Exchange 2013 specific problem.

This should be fixable modifying the code by adding `AsyncAgentContext.Resume()` (http://blogs.msdn.com/b/dvespa/archive/2013/02/18/exchange-2013-async-agent-resume-1057.aspx)

See also: http://support.threattracksecurity.com/support/discussions/topics/1000059425

**Comment by Pro** [comment]
@kimurin Can you please try the .dll from here:
https://github.com/Pro/dkim-exchange/tree/master/Src/Exchange.DkimSigner/bin

I tried adding the `Resume()` which should eliminate the message in the event viewer?!

**Comment by kimurin** [comment]
Yep, errors are gone. Thanks!

**Comment by mrrogers75** [comment]
This issue is still happening in 2.1.8, but not all the time.

**Comment by mr-flibble** [comment]
Same problem, I did update to 2.1.8 yesterday and event log is today filled with:
**Agent 'Exchange DkimSigner' went async but did not call Resume on the new thread, while handling event 'OnCategorizedMessage'**

Until yesterday I have 2.1.4 version without this error. 

I have W 2012 R2, Exchange 2013 CU7

You can see how often is it:


>Error	22. 12. 2015 9:18:59	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 8:58:58	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 8:38:59	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 8:18:58	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 8:03:56	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 7:43:56	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 7:23:57	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 7:03:57	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 6:43:57	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 6:23:56	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 6:08:54	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 5:48:54	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 5:28:55	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 5:13:52	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 4:53:53	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 4:33:53	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 4:13:53	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 3:53:53	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 3:38:51	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 3:23:49	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 3:04:54	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 2:48:51	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 2:28:51	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 2:08:50	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 1:48:50	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 1:28:49	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 1:13:46	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 0:33:59	MSExchange Extensibility	1057	MExRuntime
Error	22. 12. 2015 0:11:36	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 23:51:37	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 23:31:37	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 23:11:37	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 22:56:34	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 22:36:35	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 22:16:34	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 21:56:34	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 21:36:34	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 21:16:34	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 20:56:35	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 20:41:32	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 20:21:32	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 20:01:33	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 19:41:33	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 19:21:32	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 19:01:32	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 18:46:30	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 18:26:30	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 18:06:30	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 17:46:30	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 17:26:30	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 17:06:30	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 16:51:27	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 16:31:28	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 16:11:28	MSExchange Extensibility	1057	MExRuntime
Error	21. 12. 2015 15:53:40	MSExchange Extensibility	1057	MExRuntime

**Comment by gogglespisano** [comment]
On the surface it looks like GetAgentAsyncContext(), Resume() and Complete() should only be used if the event is handled asynchronously, which it isn't.  Maybe the answer is just to remove all 3 calls?
