### ISSUE TITLE
Exchange 2013 CU10

### ISSUE THREAD

**Issue by pavelkos** [Pro/dkim-exchange#98]
Please add support for Exchange 2013 CU10. Which files from CU10 I'm need to upload ?

**Comment by Pro** [comment]
```
C:\Program Files\Microsoft\Exchange Server\V15\Public
Microsoft.Exchange.Data.Common.dll
Microsoft.Exchange.Data.Common.xml
Microsoft.Exchange.Data.Transport.dll
Microsoft.Exchange.Data.Transport.xml
```

**Comment by pavelkos** [comment]
https://dl.dropboxusercontent.com/u/11127662/CU.10.Public.zip

**Comment by Pro** [comment]
See https://github.com/Pro/dkim-exchange/releases/tag/v2.1.7

Please let me know if there are any problems
